export const initialStates = {
  logo: null,
  coverPhoto: null,
  additionalPhotos: [],
  organizerBio: "",
  organizerName: "",
  organizationAttributes: {
    asianOwned: false,
    veteranOwned: false,
    LGBTQfriendly: false,
    hispanicLatinxOwned: false,
    womenOwned: false,
    indigenousOwned: false,
    blackOwned: false,
    wheelchairAccessible: false,
    LGBTQowned: false,
  },
  saftyAndCleaness: {
    vaccinationPolicies: false,
    maskWearingPolicies: false,
    socialDistancingMeasures: false,
    ventilationSystem: false,
    extraSanitation: false,
    limitedCapacity: false,
    contactlessCheckIn: false,
    temeratureChecks: false,
    equipmentPolicies: false,
  },

  phoneNumber: "",
  twitter: "",
  facebook: "",
  youtube: "",
  instagram: "",
};
