import React from "react";
import {HeadingWithContent} from "../../components";
import {PrivacyPolicyStyle} from "./PrivacyPolicy.style";
import {useHistory} from "react-router";

export default function PrivacyPolicy() {
    const history = useHistory();
    return (
        <PrivacyPolicyStyle>
            <HeadingWithContent
                handleButtonClick={() => {
                    history.goBack()
                }}
                heading="Privacy Policy"
                content={[
                    "(last updated April 27, 2022)",
                    "MusicPass respects your right to privacy. This Privacy Notice explains who we are, how we collect, share and use personal information about you, and how you can exercise your privacy rights. This Privacy Notice only applies to personal information that we collect through our website at MusicPass.com and our mobile applications (collectively, the “Site”). This Privacy Notice applies to you if you use our Site in the US.",
                    "If you have any questions or concerns about our use of your personal information, then please contact us using the contact details provided at the bottom of this Privacy Notice.",
                    "The Site is not intended for or directed to persons under the age of 18, and we will not knowingly collect information from persons under 18. To provide information to us through registration or in any other manner on the Site, you must be 18 years of age or older.",
                    "1. What Does MusicPass Do?",
                    "MusicPass enables consumers to find, book and attend a wide range of fitness, recreational and wellness eventes, services or products offered and operated by fitness studios, gyms, trainers, venues or other third parties through our platform. MusicPass LLC, is headquartered in the United States. MusicPass group companies operate all around the world.",
                    "2. What Personal Information Does MusicPass Collect?",
                    "We collect or receive personal information in a few different ways via the Site. Often, you choose what information to provide, but sometimes we require certain information in order for you to use, and for us to provide you with, the Site and the experiences you reserve or access through the Site.",
                    "Data You Provide To Us.",
                    "There are a variety of different ways you may provide data to us, such as:",
                    "Account Creation. To create an account, you need to provide data including information such as your name, email address, phone number, sign-up city and a password. If you make a purchase or sign up for a subscription, you will need to provide payment and billing information. You can choose to add further information to your account, such as birthdate, gender, photo and address.\n" +
                    "Profile. To complete your profile, you may provide other information, such as a photo or birthdate.\n" +
                    "Posting and Uploading. We collect personal information from you when you provide, post or upload it to our Site, such as when you respond to a survey or provide a event rating or review.\n" +
                    "Third Party Data. You may not provide information to us about someone else unless you have obtained the prior consent of the other person for us to receive and use their information, such as for emergency contact or referral purposes.\n" +
                    "Data Collected Automatically Through Your Use of the Site.\n" +
                    "We log usage data when you visit or otherwise use our Site, such as when you view or click on content or ads (on or off our Site), perform a search, browse, schedule a reservation and install or update one of our mobile apps. Specifically, the information we collect automatically may include information like internet protocol (“IP”) address, device type, unique device identification numbers, browser-type, broad geographic location (e.g. country or city-level location), language and marketing preferences and other technical information. We may also collect information about how your device has interacted with our Site, including the pages accessed and links clicked.\n" +
                    "We may also collect precise geolocation data pertaining to your mobile device, if you have consented to providing this to us through your device settings. We may use this information to provide, promote, and improve our services (for example, by showing you eventes that are close to your location) and for related reasons, such as fraud prevention and security purposes. Please note that if you do not consent to providing your geolocation data, certain features of the mobile application may not work.\n" +
                    "Data Collected When You Connect To A Third Party Network.\n" +
                    "Where we make this available, you may choose to sync your account details with a third party network, such as Facebook. If you do this, we will receive some of your Facebook account information. Exactly what information we receive will depend on your settings with the third party network, but typically we receive your basic public profile information such as your username, email address, age range, gender, chosen language, country, friends list and any other public information.\n",
                    "3. What Does MusicPass Do with the Personal Information it Collects?",
                    "MusicPass uses personal information it receives for several purposes:\n" +
                    "\n" +
                    "Site: To operate and maintain our Site and the products and services offered through our Site. For example, we use personal information to fulfill your reservation and purchase requests, including processing payments, and to customize your experience on our Site, such as by tailoring the content or experiences we show you.\n" +
                    "Communication: To contact you through email, phone, postal mail, notices and/or push notifications posted on our websites or apps, and other ways. We will send you messages about the availability of our Site, security, customer service, or other service-related issues. We also send messages about the Site, updates, reminders, and promotional messages in accordance with your communications preferences. You may change your communication preferences at any time. Please be aware that you cannot opt-out of receiving service messages from us, including security and legal notices.\n" +
                    "Customer Support: In connection with customer service inquiries and matters, such as to investigate, respond to and resolve complaints and service issues.\n" +
                    "Social: To provide features which allow you to connect with, and be found by, other users.\n" +
                    "Marketing: For marketing purposes, such as to develop our marketing strategy and offer contests, sweepstakes, or other promotions and to fulfill any related awards or discounts;\n" +
                    "Research and Development: For research, analytical, recordkeeping, and reporting purposes; to develop and test new products, features and ideas; to learn about our customer base and Site and to evolve and improve our Site, products and services.\n",
                    "Security and Investigations: We use your information to maintain the security of our Site, including to verify your identity, to investigate or prevent possible fraud or other violations of our Terms of Use or this Privacy Notice and/or in connection with possible attempts to harm our members, visitors, studio partners or other third parties.\n" +
                    "Other: For any other purpose identified at the point of collection or otherwise with your consent.",
                    "4. Who Does MusicPass Share My Personal Information With?\n" +
                    "We may disclose your personal information to the following categories of recipients or in the following circumstances:",
                    "your name, photo and other information associated with your account will be visible to other MusicPass members so that they can search for and connect with you on MusicPass. You can prevent other users from being able to search for you by updating your preferences via the Privacy tab in your Account Settings;\n" +
                    "If you sync your account to a third party network, such as Facebook, or provide us with your contacts, such as those stored on your mobile device, you will be able to see which of your contacts are using MusicPass. If those contacts are MusicPass members, they will also be able to see that you are using MusicPass;\n" +
                    "If you accept a friend request from another MusicPass member then, in addition to your name, photo and other information associated with your account, that MusicPass member will also be able to see your past and upcoming eventes, your achievement badges, your favorite studios, your friend connections and other profile information (together, “Profile Information”). We may use, communicate and display your Profile Information next to or in connection with ads, offers, and other messages to your MusicPass friends - for example, by sending an email to one of your MusicPass friends to suggest that they join you in event. If you would like to stop your Profile Information being shared with your MusicPass friends in this way, you can do so via the Privacy tab in your Account Settings;\n" +
                    "to anyone who visits our Site if you share information about yourself in a public area on our Site, such as in your public profile, a review or a event rating. You should be aware that any content or information you choose to disclose in these areas can be read, collected and used by other users, the general public and other sites (including search engines);\n" +
                    "to any competent law enforcement body, regulatory, government agency, court or other third party where we believe disclosure is necessary as a matter of applicable law or regulation, to exercise, establish or defend our legal rights, or to protect your vital interests or those of any other person;\n" +
                    "in connection with an actual or potential merger, sale, acquisition, investment, assignment, reorganization, joint venture, or transfer of all or part of MusicPass’ business, assets, affiliates, including if MusicPass should ever file for bankruptcy or a related proceeding, provided that we inform the relevant third party it must use your personal information only for the purposes disclosed in this Privacy Notice;\n" +
                    "to your program administrator (such as your employer or similar entity), if you participate in any enterprise solutions or the MusicPass Corporate Program; and\n" +
                    "to any other person with your consent to the disclosure or otherwise in accordance with applicable law.",
                    "5. How does MusicPass Keep My Personal Information Secure?",
                    "We use reasonable security procedures and practices appropriate to the nature of the information to protect the personal information that we collect and process about you. The measures we use are designed to provide a level of security appropriate to the risk of processing your personal information. We monitor our systems for possible vulnerabilities and attacks. However, we cannot guarantee 100% security of any information that you send us.",
                    "6. Your data protection rights",
                    "You have the following data protection rights:",
                    "you may correct, amend, or delete your personal information by editing your profile on the Site or contacting us.\n" +
                    "you have the right to opt-out of receiving direct marketing communications we send you at any time. You can exercise this right by clicking on the “unsubscribe” or “opt-out” link in the marketing e-mails we send you. To opt-out of other forms of marketing (such as postal marketing or telemarketing), then please contact us.\n" +
                    "residents in California (and other states where required by law) have certain rights with respect to the personal information collected by businesses. If you are a resident of any such state, you may exercise the following rights regarding your personal information, subject to certain exceptions and limitations:\n" +
                    "for certain categories of personal information, the right to request a list of what personal information (if any) we disclosed to third parties for their own direct marketing purposes in the preceding calendar year and the names and addresses of those third parties;\n" +
                    "the right to know the categories and specific pieces of personal information we collect, use, disclose, and sell about you, the categories of sources from which we collected your personal information, our purposes for collecting or selling your personal information, the categories of your personal information that we have either sold or disclosed for a business purpose, and the categories of third parties with which we have shared personal information;\n" +
                    "the right to request that we delete the personal information we have collected from you or maintain about you;\n" +
                    "the right to opt out of our sale(s) of your personal information (if any); and\n" +
                    "the right not to receive discriminatory treatment for the exercise of the privacy rights conferred by the CCPA.\n" +
                    "You may designate an authorized agent to make a request on your behalf. You can do this by authorizing your agent to access your MusicPass account and making a request on your behalf by contacting us. We respond to all requests we receive from individuals wishing to exercise their data protection rights in accordance with applicable data protection laws.\n",
                    "7. Third Party Sites",
                    "Our Site may contain links to third-party websites or mobile apps, including social sharing features and other related tools. Please be aware that MusicPass does not control these linked websites or apps and that this Privacy Notice does not apply to any information you give to the owner of these websites or apps. We encourage you to read the privacy policy of any third-party website or app that you visit before you provide them with any information.",
                    "8. Your consent to this Privacy Policy",
                    "By using our Site, you agree to this Privacy Policy. We may occasionally update this Privacy Policy. The date of the most recent update of this document will always be displayed at the beginning of this page. If we change our Privacy Policy, we will post those changes on MusicPass.com. If we decide to use personal information in a manner different from that stated at the time it was collected, we will notify users via email (if an email address has been provided) or display a notice on MusicPass.com. We encourage you to periodically review this Privacy Policy to stay informed about how we are protecting the personal information we collect. Your continued use of this Site constitutes your agreement to this Privacy Policy and any updates.",
                    "9. How to contact us",
                    "If you have any questions or concerns about our use of your personal information, please contact us at:",
                    "MusicPass LLC 4000 Ponce De Leon Blvd, Ste 470, Coral Gables, FL 33146",
                    "Or contact us here.",
                    "Cookie Notice",
                    "(last updated April 25, 2022)",
                    "This Cookie Notice explains how MusicPass and its subsidiaries (collectively “MusicPass”, “we”, “us”, and “ours” use cookies and similar technologies to recognize you when you visit our websites and use our mobile applications (“Site”). It explains what these technologies are and why we use them, as well as your rights to control our use of them.",
                    "What are cookies?",
                    "Cookies are small data files that are placed on your computer or mobile device when you visit a website. Cookies are widely used by website owners in order to make their websites work, or to work more efficiently, as well as to provide reporting information. Cookies set by the website owner (in this case, MusicPass) are called \"first party cookies\". Cookies set by parties other than the website owner are called \"third party cookies\". Third party cookies enable third party features or functionality to be provided on or through the website (e.g. like advertising, interactive content and analytics). The parties that set these third-party cookies can recognize your computer both when it visits the website in question and also when it visits certain other websites.",
                    "Why do we use cookies?",
                    "We use first party and third-party cookies for several reasons. Some cookies are required for technical reasons in order for our Sites to operate, and we refer to these as \"essential\" or \"strictly necessary\" cookies. Other cookies also enable us to track and target the interests of our users to enhance the experience on our Websites. Third parties serve cookies through our Sites for advertising, analytics and other purposes. This is described in more detail below.",
                    "First and third-party cookies served through our Sites and the purposes they perform are described below:",
                    "Essential website cookies: These cookies are strictly necessary to provide you with services available through our Sites and to use some of its features, such as access to secure areas.\n" +
                    "Performance and functionality cookies: These cookies are used to enhance the performance and functionality of our Sites but are non-essential to their use. However, without these cookies, certain functionality may become unavailable.\n" +
                    "Analytics and customization cookies: These cookies collect information that is used either in aggregate form to help us understand how our Sites are being used or how effective our marketing campaigns are, or to help us customize our Sites for you.\n" +
                    "Advertising cookies: These cookies are used to make advertising messages more relevant to you and they perform functions like preventing the same ad from continuously reappearing and in some cases selecting and displaying advertisements to you across the internet that are based on your interests.\n" +
                    "Social networking cookies: These cookies are used to enable you to share pages and content that you find interesting on our Sites through third party social networking and other websites. These cookies may also be used for advertising purposes too.\n" +
                    "What about other tracking technologies?\n" +
                    "Cookies are not the only way to recognize or track visitors to a website. We may use other, similar technologies from time to time, like web beacons (sometimes called \"tracking pixels\" or \"clear gifs\"). These are tiny graphics files that contain a unique identifier that enable us to recognize when someone has visited our Sites or opened an e-mail that we have sent them. This allows us, for example, to monitor the traffic patterns of users from one page within our Sites to another, to deliver or communicate with cookies, to understand whether you have come to our Sites from an online advertisement displayed on a third-party website, to improve site performance, and to measure the success of e-mail marketing campaigns. In many instances, these technologies are reliant on cookies to function properly, and so declining cookies will impair their functioning.\n",
                    "Our mobile applications may include third-party application software development kits that provide mobile performance and analytics data, bug reporting features, and APIs to third parties that help provide the Site, for social media functionality, and for marketing and advertising.",
                    "Does MusicPass serve targeted advertising?",
                    "As described above, third parties may serve cookies on your computer or mobile device through the Sites to serve advertising. These companies may use information about your visits to this and other websites in order to provide relevant advertisements about goods and services that you may be interested in. They may also employ technology that is used to measure the effectiveness of advertisements. This can be accomplished by them using cookies or web beacons to collect information about your visits to this and other sites in order to provide relevant advertisements about goods and services of potential interest to you. The information collected through this process does not enable us or them to identify your name, contact details or other personally identifying details unless you choose to provide these.",
                    "How can I control cookies?",
                    "You have the right to decide whether to accept or reject cookies. You can exercise your cookie preferences for certain third-party cookies by clicking on the appropriate opt-out links provided above. You can also set or amend your web browser controls to accept or refuse cookies. If you choose to reject cookies, you may still use our Site though your access to some functionality and areas of our website may be restricted, you may worsen your overall user experience, since it will no longer be personalized to you and it may also stop you from saving customized settings like login information. As the means by which you can refuse cookies through your web browser controls vary from browser-to-browser, you should visit your browser's help menu for more information. To revoke consent, users may disable cookies by modifying their browser settings. The links listed below provide more information about what cookies are installed, how to allow, block or remove installation from your computer. Depending on which browser you use, the user may follow these links:",
                    "Firefox: https://support.mozilla.org/en-US/products/firefox/protect-your-privacy/cookies",
                    "Chrome: http://support.google.com/chrome/bin/answer.py?hl=es&answer=95647\n",
                    "Safari: http://support.apple.com/kb/ph5042",
                    "Explorer: http://windows.microsoft.com/es-es/windows7/how-to-manage-cookies-in-internet-explorer-9",
                    "In addition, most advertising networks offer you a way to opt out of targeted advertising. If you would like to find out more information, please visit http://www.aboutads.info/choices/, https://www.networkadvertising.org/, or http://www.youronlinechoices.com. Please bear in mind that there are many more networks listed on that site than those that we use on our Website.",
                    "We use Google cookies for analytics and marketing purposes. You can opt-out of Google tracking through Google Ads Settings, Ad Settings for mobile apps, or any other available means. Google also provides a Google Analytics opt-out plug-in for the web.",
                    "What is Do Not Track (DNT)?",
                    "DNT is a concept that has been promoted by regulatory agencies such as the U.S. Federal Trade Commission (FTC), for the Internet industry to develop and implement a mechanism for allowing Internet users to control the tracking of their online activities across websites by using browser settings. The World Wide Web Consortium (W3C) has been working with industry groups, Internet browsers, technology companies, and regulators to develop a DNT technology standard. While some progress has been made, it has been slow. No standard has been adopted to this date. As such, MusicPass does not generally respond to \"do not track\" signals.",
                    "How often will this Cookie Notice be updated?",
                    "We may update this Cookie Notice from time to time in order to reflect, for example, changes to the cookies we use or for other operational, legal or regulatory reasons. Please therefore revisit this Cookie Notice regularly to stay informed about our use of cookies and related technologies.",
                    "The date at the top of this Cookie Notice indicates when it was last updated.",
                    "Where can I get further information?",
                    "If you have any questions about our use of cookies or other technologies, please contact us here."

                ]}
            />
        </PrivacyPolicyStyle>
    );
}
