import React, {useEffect, useState} from "react";
import {TermsOfUseStyle} from "./TermsOfUse.style";
import {useHistory} from "react-router";
import {HeadingWithContentStyle} from "../../components/HeadingWithContent/HeadingWithContent.style";
import {Link} from "react-router-dom";
import {LeftChevronIcon} from "../../assets";

export default function AboutUs() {
    const history = useHistory();

    const [reservation,setReservation]=useState(null);


    useEffect(() => {
        const reservation: any = document && document?.getElementById('3c');
        setReservation(reservation);
    }, [])



    useEffect(()=>{
        var url = new URL(window.document.URL);
        var c3 = url.searchParams.get("3c");

        if(c3 && reservation){
            const reservation: any = document && document?.getElementById('3c');
            reservation.scrollIntoView();
        }

    },[reservation])

    const content=<>
        <p className="description-without-margin" style={{marginTop:"-25px"}}>(last updated April 25, 2022)</p>
        <p className="description-without-margin">Welcome to MusicPass! These Terms of Use ("Terms") are a contract between you and MusicPass LLC ("MusicPass" or "we") and govern your access to and use of any MusicPass website, mobile application (such as for iPhone or Android) or content (the "Site") or any reservations, experiences, activities, events, services, recordings, and/or products made available through MusicPass (collectively, "Reservations"). Please read these Terms carefully before accessing and/or using the Site and/or Reservations.</p>
        <p className="description-without-margin">THESE TERMS CONTAIN A BINDING ARBITRATION AGREEMENT AND EVENT ACTION WAIVER THAT REQUIRE YOU TO ARBITRATE ALL DISPUTES YOU HAVE WITH EVENT PASS ON AN INDIVIDUAL BASIS. PLEASE SEE SECTION 18 FOR MORE INFORMATION ABOUT THE ARBITRATION AGREEMENT AND EVENT ACTION WAIVER. YOU EXPRESSLY AGREE THAT DISPUTES BETWEEN YOU AND MUSICPASS WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION, AND YOU HEREBY WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR EVENT WIDE ARBITRATION.</p>
        <p className="description-without-margin">1. Terms of Use.</p>
        <p className="description-without-margin">a) Acceptance of Terms. By accessing and/or using the Site and/or Reservations, or clicking any button to indicate your consent, you accept and agree to be bound by these Terms, just as if you had agreed to these Terms in writing. If you do not agree to these Terms, do not use the Site or any Reservations.</p>
        <p className="description-without-margin">b) Amendment of Terms. MusicPass may amend the Terms from time to time. Unless we provide a delayed effective date, all amendments will be effective upon posting of such updated Terms. Your continued access to or use of the Site or Reservations after such posting constitutes your consent to be bound by the Terms, as amended.</p>
        <p className="description-without-margin">c) Additional Terms. In addition to these Terms, certain plans, offers, products, services, elements or features may also be subject to additional terms, conditions guidelines or rules which may be posted, communicated or modified by us or applicable third parties at any time. Your use of any such plan, offer, product, service, element or feature is subject to those additional terms and conditions, which are hereby incorporated by reference into the Terms, provided that in the event of any conflict between such additional terms and the Terms, the Terms shall control. The MusicPass Privacy Policy is hereby incorporated by reference.</p>
        <p className="description-without-margin">2. MusicPass Platform</p>
        <p className="description-without-margin">a) MusicPass Platform. The MusicPass platform enables consumers to reserve, schedule, purchase, access and attend a wide range of live music events reservations offered and operated by event hosts or other third parties (collectively, "Partners"). MusicPass itself is not a place of amusement or recreation, venue, facility, or similar establishment and does not own, operate or control any of the Reservations that are offered at or through such facilities.</p>
        <p className="description-without-margin">b) Membership Options. There are a number of ways to participate in Reservations through MusicPass, such as various subscription plans, promotional plans, and non-subscription purchases. These options consist of different reservations, services and features and may be subject to additional and differing conditions, prices, policies and limitations. We reserve the right to modify, terminate or otherwise amend our offered options and plans at any time in our discretion. From time to time we may permit non-subscribers to access certain Reservations, content or features for a cost or at no cost. MusicPass makes no commitment on the quantity, availability, type or frequency at which such Reservations, content and features will be available to non-subscribers and may modify, discontinue, remove or suspend access at any time and for any reason in our sole discretion.</p>
        <p className="description-without-margin">c) Subscription Plans. To enjoy full access to the Site and Reservations, you need to sign up for a subscription. A subscription starts on the date that you sign up for a subscription and submit payment via a valid Payment Method (defined below) or reactivate a pre-existing subscription. Unless we otherwise communicate a different time period to you at the time of sign up or otherwise (such as a multi-month commitment plan), each billing cycle is one month in length (a "Subscription Cycle"). Your MusicPass subscription automatically renews each month, and we will automatically bill the monthly subscription fee to your Payment Method each month, until your subscription is cancelled or terminated. For example, if you purchase your MusicPass subscription on April 5, your subscription will automatically renew on May 5 (as further explained in "Subscription Cycles," below). You must provide us with a current, valid, accepted method of payment ("Payment Method"). We may update the accepted methods from time to times. If you add a subscription to your base subscription or if you upgrade or downgrade to a different subscription, all such subscriptions will be governed by these Terms and will continue indefinitely until canceled or terminated.</p>
        <p className="description-without-margin">d) Use of Credits. Depending on the subscription plan you choose and purchase, you will be allotted credits to be used solely to book Reservations each Subscription Cycle. You can choose how you use your credits across the various Reservations available to you.</p>
        <p className="description-without-margin">Credits expire at the end of each Subscription Cycle, meaning that any credits you don’t use during the applicable Subscription Cycle will not roll over into future months, unless we expressly communicate otherwise. You can find more information about the current rollover policies here. You can see how many days you have left in each Subscription Cycle in your account settings. If your subscription is canceled or terminated your unused credits will expire immediately. There will be no refund or payment for any unused amount. When your cycle automatically renews for the next month, you’ll automatically receive your new allotment of credits. If you have any questions about how to use your credits, please contact us and we can help you.</p>
        <p className="description-without-margin">Credits have no cash value or any other value outside of the MusicPass platform and are not redeemable for cash. For the avoidance of doubt, the credits do not operate or serve as stored value facilities in any way. You may not transfer, trade, gift or otherwise exchange MusicPass credits.</p>
        <p className="description-without-margin">e) Event Availability and Allocation. The exact number and type of Reservations you take during any Subscription Cycle will depend on the number of credits needed to book the particular Reservations you select. The number of credits needed to book a particular Event will vary and is determined based on a variety of factors, including but not limited to Venue requirements, time of day, featured artists, facilities, location, pricing, popularity and other characteristics. For example, an Event offered at a peak time like a Saturday night is likely to require more credits to book than a similar Event offered on a Wednesday night. Or, an Event that features premium artists is likely to require more credits to book than an event with lesser-known artists. Furthermore, a Venue may require more credits for a certain Event under certain circumstances, such as during a holiday weekend. Note that credits needed to book Reservations also vary from city to city. Accordingly, if MusicPass permits you to reserve reservations in a city that differs from your home location, your credits may enable you to reserve more or fewer reservations when you are traveling from your home location. As such, the number of credits you need to reserve a particular Event or service may change at any time or vary day to day depending on the factors described here. MusicPass also reserves the right to change the number of credits you receive, including per cycle, plan, geography or otherwise; the number of reservations you can make; and/or the number of Reservations you can miss or cancel.</p>
        <p className="description-without-margin">MusicPass does not guarantee the availability of particular Venues, locations, Reservations, services, experiences, content, inventory, spots or other features, and availability may change over time and at any time (including during the course of any given Subscription Cycle). The type, quantity, credits, allocation and availability of Venues, reservations, and other inventory offered, are determined by MusicPass in its sole discretion. MusicPass takes certain steps to release, promote and otherwise make available spots and inventory at varying times and in an ongoing and evolving way.</p>
        <p className="description-without-margin">f) Non-Subscription Purchases. MusicPass may permit you to purchase certain products or Reservations through the Site, in addition to your subscription or without having a subscription. You acknowledge and agree that these Terms apply to any such purchase you make, and you will be responsible to pay the applicable fees, which may change at any time.</p>
        <p className="description-without-margin">g) MusicPass Account. Your MusicPass account is personal to you and you agree not to create more than one account. You cannot transfer or gift Reservations or credits to third parties or allow third parties to use your MusicPass account, including other MusicPass users. You must not use or exploit the Site and/or Reservations for commercial purposes. We continually update and test various aspects of the MusicPass platform. We reserve the right to, and by using the Site and/or Reservations you agree that we may, include you in or exclude you from these tests without notice. You understand and agree that MusicPass may take actions we deem reasonably necessary to prevent fraud and abuse.</p>
        <p className="description-without-margin">You agree that the information you provide to MusicPass at sign up and at all other times will be true, accurate, current, and complete and that you will keep this information accurate and up-to-date at all times. When you sign up, you will be asked to create a password. You are solely responsible for all activity that occurs under your account, including any activity by unauthorized users. To use the Site you must have access to the Internet and may be required to download a MusicPass mobile application to use some or all of MusicPass features. You are solely responsible for providing your own access (e.g., computer, mobile device, Internet connection, etc.) to the Site and Reservations.</p>
        <p className="description-without-margin">h) Eligibility. The availability of all or part of our Site and/or Reservations may be limited based on geographic, age, or other criteria as we may establish from time to time. You understand and agree we may disallow you from subscribing to MusicPass or may terminate your subscription at any time based on these criteria. For example, you must be 18 years of age or older to use the Site and/or Reservations and/or purchase a MusicPass subscription. You further understand that the Site and/or Reservations may not be available in every geography.</p>
        <p className="description-without-margin">MUSICPASS CURRENTLY OPERATES SOLELY IN THE UNITED STATES.</p>
        <p className="description-without-margin">THESE TERMS ARE ONLY APPLICABLE TO USERS IN THE U.S. THE SITE IS NOT AVAILABLE TO ANY USERS SUSPENDED OR REMOVED FROM THE SITE BY MUSICPASS. BY USING THE SITE, YOU REPRESENT THAT YOU ARE A RESIDENT OF THE UNITED STATES, AT LEAST 18 YEARS OLD AND HAVE NOT BEEN PREVIOUSLY SUSPENDED OR REMOVED. THOSE WHO CHOOSE TO ACCESS THE SITE DO SO AT THEIR OWN INITIATIVE AND ARE RESPONSIBLE FOR COMPLIANCE WITH ALL LOCAL RULES INCLUDING, WITHOUT LIMITATION, RULES ABOUT THE INTERNET, DATA, EMAIL OR OTHER ELECTRONIC MESSAGES, OR PRIVACY.</p>
        <p className="description-without-margin">i) Communications: By providing your information or creating an account, you agree that MusicPass may contact you by email, direct mail, telephone or text messages at any of the addresses or phone numbers, as applicable, provided by you or on your behalf in connection with a MusicPass account, including for marketing purposes. You may opt-out of marketing emails via the provided unsubscribe link or otherwise opt-out by contacting us at any time.</p>
        <p className="description-without-margin">j) Subscribing Organizations. If you have express permission from MusicPass to open or use an account on behalf of a company, entity, or organization (a "Subscribing Organization"), then you represent and warrant that you are an authorized representative of such organization with the authority to bind such it to these Terms; and agree to be bound by these Terms on its behalf.</p>
        <p className="description-without-margin">3. Fees, Billing, Cancellation</p>
        <p className="description-without-margin">a) Recurring Billing. By initiating a MusicPass subscription, you authorize us to charge you for your initial subscription period and a recurring monthly subscription fee at the then current rate, which may change from time to time. You acknowledge that the amount billed each month may vary for reasons that may include differing amounts due to promotional offers and/or changing or adding a plan, and you authorize us to charge your Payment Method for such varying amounts, which may be billed monthly in one or more charges. You also authorize us to charge you any other fees you may incur in connection with your use of the Site, such as any applicable sign-up fee, taxes and cancellation or late fees, as further explained below. Note that even if you do not use the subscription or access the Site and/or Reservations, you will be responsible for subscription fees until you cancel your subscription, or it is otherwise terminated.</p>
        <p className="description-without-margin" id={"3c"}>b) Subscription Cycle. When you sign up and purchase your MusicPass subscription, your first Subscription Cycle will be billed immediately. Unless we expressly communicate otherwise, your subscription will automatically renew each month and you will be billed on the same date each month. We reserve the right to change the timing of our billing (and if we do, we’ll make adjustments to the amounts we charge, as appropriate). In the event your paid subscription began on a day not contained in a given month, we may bill your Payment Method on a day in the applicable month or such other day as we deem appropriate. For example, if you started your MusicPass membership or became a paying member on January 31st, your next payment date is likely to be February 28th, and your Payment Method would be billed on that date. Your renewal date may change due to changes in your subscription.</p>
        <p className="description-without-margin">c) Refunds. Generally, our fees (including the monthly fee for your membership and any other fees) are nonrefundable unless we specifically communicate otherwise at the time of purchase. However, we will provide a refund to subscribers for their current prepaid subscription period only in the following circumstances: (i) if you are canceling your subscription and request a refund within 5 days of the date of your first payment for your subscription or (ii) if your subscription is cancelled prior to the end of a period for which you have incurred a charge, due to your relocation, disability or death; provided, however, in each case we reserve the right to charge a fee to cover the cost of any event or other services or products you may have used or received prior to your cancellation and to ask for proof of such changed condition, to the extent permitted by law. WE DO NOT PROVIDE REFUNDS OR MAKE GOODS FOR ANY PRIOR MONTHS INCLUDING FOR UNUSED CREDITS OR RESERVATIONS.</p>
        <p className="description-without-margin">d) Price Changes. We reserve the right to adjust pricing at any time. Unless we expressly communicate otherwise, any price changes to your subscription will take effect on your next billing cycle upon notice communicated through a posting on the MusicPass website or mobile applicable or such other means as we may deem appropriate from time to time, such as email. If you do not cancel your subscription, you will be deemed to have accepted these new fees.</p>
        <p className="description-without-margin" >e) Payment Methods. You may edit your Payment Method information by logging onto our website or mobile app and editing it in your account settings. If a payment is not successfully settled due to expiration, insufficient funds or otherwise, you nonetheless will remain responsible for any uncollected amounts and authorize us to continue billing the Payment Method or any other payment method you have provided, as it may be updated, including in the event you attempt to create a new account, reactivate the unsettled account or sign up for a new account. This may result in a change to your payment billing dates. If we cannot charge your account, we reserve the right, but are not obligated, to terminate your access to our Site or any portion thereof.</p>
        <p className="description-without-margin">g) Other Fees. You are responsible for paying applicable fees if you do not cancel a Event you had reserved with appropriate notice or do not attend your scheduled Event. Click here for our current cancellation and missed Event rules, including the applicable fees. We reserve the right to change the policy regarding when we charge fees, to introduce additional fees (such as a sign-up fee) and to change the amount of any such fees at any time.</p>
        <p className="description-without-margin">h) Reservation and Cancellation of Reservations. As a MusicPass user, you must reserve and cancel your Reservations only through the Site. It is a breach of these Terms if you reserve or cancel directly with a Venue, including through any online or mobile account you have with a Venue, independent of MusicPass. If you reserve or cancel directly with such Venue, we reserve the right to charge you the full amount that the Venue charges for such event and/or any applicable cancellation fees, and/or to suspend or terminate your subscription.</p>
        <p className="description-without-margin">i) Fees Charged by Venues. In addition to fees we charge, Venues may also charge equipment or other amenity fees that you will be responsible for directly. For example, some Venues might charge extra to rent a yoga mat or cycling shoes. Further, MusicPass only gives you access to the event for which you signed up on the Site (and at the specified time and location). The Venue may have additional fees for use of additional reservations or spaces.</p>
        <p className="description-without-margin">j) Third Party Fees for Using MusicPass. You are also responsible for all third-party charges and fees associated with connecting to and using the Site and/or Reservations, including fees such as internet service provider fees, telephone and computer equipment charges, sales tax and any other fees necessary to access the Site and/or Reservations.</p>
        <p className="description-without-margin">4. Promotions</p>
        <p className="description-without-margin">a) Trials. From time to time we may offer a trial membership that includes access to the MusicPass platform during the trial period. The Reservations, content and features available during your Trial may differ from those available during subsequent Subscription Cycles. Trials will have the duration and price communicated at the time you sign up. Unless otherwise communicated, a trial begins at the moment of sign up (even if you choose not to take your first Event until a later date) and ends at 11:59pm ET on the last day of the trial (for a one-week trial, this would be the same weekday of following week). If you cancel your Trial, your cancellation will be processed and your Trial period will end immediately, your credits will expire, and your upcoming reservations will be cancelled, unless we communicate otherwise. Each trial membership automatically will convert to a regular monthly subscription and price unless canceled by 12pm ET on the day before the last day of trial. Customers that cancel and do not convert to a regular subscription may not attend reservations taking place after the end of the trial membership period (even if booking occurred before the end of the applicable trial period). Trials, discount offers, and promotions (collectively "Trials") may be redeemed as described in the specifics of the promotion and may be subject to additional or different terms. Unless we expressly communicate otherwise, Trials are not transferable, may not be combined with other offers or redeemed for cash and are void where prohibited. You understand and agree that unless we expressly communicate otherwise, Trials are available only to new users that have never had a MusicPass account before and there is only one Trial permitted per credit card or payment method and it is a violation of these Terms to sign up for a Trial if you have signed up for an account or trial in the past or to have more than one account or trial at the same time. MusicPass reserves the right, in its absolute discretion, to determine your eligibility for a Trial. If in our discretion we believe you are not eligible for a Trial, we reserve the right to prevent you from signing up for a Trial or to terminate your promotional subscription. If we terminate your Trials because you have violated these Terms, you understand that you will not be eligible for a refund.</p>
        <p className="description-without-margin">b) Other Promotions. MusicPass may offer additional types of offers and promotions which will be subject to additional terms and conditions that MusicPass may provide.</p>
        <p className="description-without-margin">5. Termination or Modification by MusicPass.</p>
        <p className="description-without-margin">You understand and agree that, at any time and without prior notice MusicPass may (1) terminate, cancel, deactivate, disable, delete and/or suspend your subscription, your account, any orders placed, or your access to or use of the Site, your membership and/or Reservations (or any portion thereof, including but not limited to your access to any or all Venues, credits or reservations or services) and/or (2) discontinue, disable, suspend, modify or alter any aspect, feature or policy of the Site , including of your subscription. This includes the right to terminate or modify any subscription prior to the end of any pre-paid or committed period. Upon any termination or otherwise, we may immediately deactivate your account and all related information and/or bar any further access to your account information and the Site. MusicPass shall have no liability for, and you shall have no recourse for, any such termination or deactivation, except as set forth in the following sentence. If you are subscriber, then upon any such termination by us without cause, as your sole recourse, we will issue you a pro rata refund of the prepaid portion of your subscription applicable to future unused services (less any fees or costs for reservations or services already used). If we determine that you have violated these Terms or otherwise engaged in illegal or improper use of your membership, Reservations and/or the Site, you will not be entitled to any refund and you agree that we will not be responsible to pay any such refund. You agree that MusicPass will not be liable to you or any third party for any termination or modification to the service regardless of the reason for such termination or modification. You acknowledge that your only right with respect to any dissatisfaction with any modification or discontinuation of service made by us is to cancel or terminate your subscription. If MusicPass deletes your account for these reasons, you may not re-register for or use the Site and/or Reservations under any other user name, email, payment method or profile. MusicPass may block your access to the Site to prevent re-registration.</p>
        <p className="description-without-margin">6. Privacy.</p>
        <p className="description-without-margin">Your privacy is important to MusicPass. The MusicPass Privacy Policy is hereby incorporated into these Terms by reference. Please read the privacy policy carefully for information relating to MusicPass’ collection, use, and disclosure of your personal information. When you make a reservation, the applicable Venue partner will have access to certain information about you, such as your name and email address, so it can process the applicable reservation or activity and make available Reservations and provide services to you. Please see the Privacy Policy for more information.</p>
        <p className="description-without-margin">7. Prohibited Conduct.</p>
        <p className="description-without-margin">Without limiting the prohibitions and restrictions found elsewhere throughout the Terms, you agree not to:</p>
        <p className="description-without-margin">Harass, threaten, stalk, disrupt or defraud users, members or staff of MusicPass or Venues or any other person, or otherwise create or contribute to an unsafe, harassing, threatening or disruptive environment;</p>
        <p className="description-without-margin">Act in a deceptive or fraudulent manner by, among other things, impersonating another person or access another user’s account or signing up for more than one account;</p>
        <p className="description-without-margin">Share MusicPass passwords with any third party or encourage any other user to do so;</p>
        <p className="description-without-margin">Permit anyone to use any reservations or services booked under your own membership, including other members;</p>
        <p className="description-without-margin">Reserve or cancel any event directly with a Venue, rather than through the Site;</p>
        <p className="description-without-margin">Reproduce, modify, prepare derivative works based upon, distribute, license, lease, sell, resell, transfer, publicly display, publicly perform, transmit, stream, broadcast, use for commercial purposes or otherwise exploit any portion of the Site;</p>
        <p className="description-without-margin">Misrepresent the source, identity, or content of information transmitted via the Site, including deleting the copyright or other proprietary rights or notices from any portion of the Site;</p>
        <p className="description-without-margin">Upload material (e.g. virus) that is damaging to computer systems or data of MusicPass or users of the Site or otherwise use the Site in any manner that could damage, disable, overburden, or impair it or interfere with any other party’s use and enjoyment of the Site;</p>
        <p className="description-without-margin">Upload copyrighted material that is not your own or that you do not have the legal right to distribute, display, and otherwise make available to others;</p>
        <p className="description-without-margin">Upload or send to Site users pornographic, threatening, embarrassing, hateful, racially or ethnically insulting, libelous, or otherwise inappropriate content;</p>
        <p className="description-without-margin">Decompile, reverse engineer or disassemble the Site, in whole or in part, except as may be permitted by applicable law;</p>
        <p className="description-without-margin">Link to, mirror or frame any portion of the Site;</p>
        <p className="description-without-margin">Cause or launch any programs or scripts for the purpose of scraping, indexing, surveying, or otherwise data mining any portion of the Site or unduly burdening or hindering the operation and/or functionality of any aspect of the Site;</p>
        <p className="description-without-margin">Attempt to gain unauthorized access to or impair any aspect of the Site or its related systems or networks or interfere or attempt to interfere with the proper working of the Site or any activities conducted on the Site;</p>
        <p className="description-without-margin">Make unsolicited offers, advertisements, proposals, or send junk mail or "spam" to users;</p>
        <p className="description-without-margin">Make unsolicited offers, advertisements, proposals, or send junk mail or "spam" to users;</p>
        <p className="description-without-margin">Obtain or attempt to obtain any materials or information through any means not intentionally made available through the Site;</p>
        <p className="description-without-margin">Modify the Site in any manner or form, nor to use modified versions of the Site, including (without limitation) for the purpose of obtaining unauthorized access to the Site;</p>
        <p className="description-without-margin">Use any robot, spider, scraper, or other automated means to access the Site for any purpose without our express written permission or bypass our robot exclusion headers or other measures we may use to prevent or restrict access to the Site;</p>
        <p className="description-without-margin">Use the Site for or in connection with any purpose that is unlawful or prohibited by these Terms.</p>
        <p className="description-without-margin">MusicPass reserves the right to refuse service, terminate accounts, remove or edit content, or cancel orders in its sole discretion.</p>
        <p className="description-without-margin">8. User Submissions.</p>
        <p className="description-without-margin">a) General. The Site provides certain features which enable you and other users to submit, post, share and search for content and information, which may include (without limitation) text, graphic and pictorial works, profile information, information about reserved or attended reservations, friend connections or any other information submitted by you and other users or arising from your use of the Site (“User Submissions”). User Submissions also include reviews, ratings and other feedback (“Reviews”). We strongly recommend that you think carefully about what you upload to, share with or make accessible to the Site. MusicPass does not guarantee any anonymity or confidentiality with respect to any User Submissions. For information on how we use your personal information, please see our Privacy Policy.</p>
        <p className="description-without-margin">b) Reviews. You understand and agree that Reviews may be made public without any additional notice to or consent by you and you should assume that any person (whether or not a user of MusicPass’ platform), including any Venue, may read or have access to your Reviews. MusicPass is not responsible for the use or disclosure of any information that you disclose in connection with Reviews, including any personal information. Reviews are displayed for information purposes only and reflect the opinions of the person making the submission. They are not controlled by, and may not reflect the opinion of, MusicPass. You understand that all Reviews are the sole responsibility of the person from whom such Review originated. This means that you, and not MusicPass, are entirely responsible for all Reviews that you upload, post, e-mail, transmit, or otherwise make available through the Site.</p>
        <p className="description-without-margin">c) Right to Remove or Edit User Submissions. MusicPass makes no representations that it will publish or make available on the Site any User Submissions, and reserves the right, in its sole discretion, to refuse to allow any User Submissions on the Site, or to edit or remove any User Submission at any time with or without notice. Without limiting the generality of the preceding sentence, MusicPass complies with the Digital Millennium Copyright Act, and will remove User Submissions upon receipt of a compliant takedown notice (see the "Digital Millennium Copyright Act" section below). MusicPass may, but is not obligated to, monitor and edit or remove any activity or content, in whole or in part, including but not limited to content that MusicPass determines in its sole discretion to violate the standards of this Site. MusicPass takes no responsibility and assumes no liability for any User Submissions.</p>
        <p className="description-without-margin">d) License Grant by You to MusicPass. You retain all your ownership rights in original aspects of your User Submissions. By submitting User Submissions to MusicPass, you hereby grant MusicPass and its affiliates, sublicensees, partners, designees, and assignees of the Site (collectively, the "MusicPass Licensees") a worldwide, non-exclusive, fully paid-up, royalty-free, perpetual, irrevocable, sublicensable, and transferable license to use, reproduce (including by making mechanical reproductions), distribute, modify, adapt, translate, prepare derivative works of, publicly display, publish, publicly perform, and otherwise exploit your User Submissions and derivatives thereof in connection with the Site and MusicPass’s (and its successors’) business, for any purpose, including, without limitation, for marketing, promoting, and redistributing part or all of the Site (and derivative works thereof), in any media formats and through any media channels now known or hereafter discovered or developed.</p>
        <p className="description-without-margin">e) User Submissions Representations and Warranties. By accessing and/or using our services, you hereby grant MusicPass and its affiliates, sublicensees, partners, designees, and assignees of the Site (collectively, the “MusicPass Licensees”) a worldwide, non-exclusive, fully paid-up, royalty-free, perpetual, irrevocable, sublicensable, and transferable license to use, reproduce (including by making mechanical reproductions), distribute, modify, adapt, translate, prepare derivative works of, publicly display, publish, publicly perform, and otherwise exploit your User Submissions and derivatives thereof in connection with the Site and MusicPass’s (and its successors’) business for any purpose, including, without limitation, for marketing, promoting, and redistributing part or all of the Site (and derivative works thereof), in any media formats and through any media channels now known or hereafter discovered or developed. You acknowledge that you may have what are known as “moral rights” in your User Submissions, for example the right to be named as the creator and the right not to have work subjected to derogatory treatment. You agree to waive any such moral rights you may have in User Submissions.</p>
        <p className="description-without-margin">f) Inaccurate or Offensive User Submissions. You understand that when using the Site, you may be exposed to User Submissions from a variety of sources and that MusicPass does not endorse and is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such User Submissions. You further understand and acknowledge that you may be exposed to User Submissions that are inaccurate, offensive, indecent, or objectionable. YOU AGREE TO WAIVE, AND HEREBY DO WAIVE, ANY LEGAL OR EQUITABLE RIGHTS OR REMEDIES YOU HAVE OR MAY HAVE AGAINST MUSICPASS WITH RESPECT THERETO.</p>
        <p className="description-without-margin">g) Feedback. If you provide MusicPass with any comments, bug reports, feedback, or modifications proposed or suggested by you to the Site ("Feedback"), MusicPass shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Site. You hereby grant MusicPass a perpetual, irrevocable, nonexclusive license under all rights necessary to incorporate and use your Feedback for any purpose without notice to, consent by or compensation to you or any third party.</p>
        <p className="description-without-margin">h) Infringing or Illegal Activity. In the event of infringing or other illegal activities, we have no obligation to, but reserve the right to terminate access to the Site and remove all content submitted by any persons who are found to be infringers. Any suspected illegal activity may be referred to appropriate law enforcement authorities. These remedies are in addition to any other remedies MusicPass may have at law or in equity.</p>
        <p className="description-without-margin">i) MusicPass Ratings. You may be required to rate your Reservations and/or other MusicPass experiences that you reserve.</p>
        <p className="description-without-margin">j) Advertising. You give us permission to use and display your User Submissions next to or in connection with ads, offers, and other messages to your MusicPass friends, without any compensation or advance notice. We may, for example, send an email to one of your MusicPass friends to encourage them to join you in an event. You can update your preferences at any time by navigating to the Privacy Settings.</p>
        <p className="description-without-margin">9. Ownership; Proprietary Rights; Content.</p>
        <p className="description-without-margin">a) The MusicPass website and mobile applications are owned and operated by MusicPass. The content, recordings, visual interfaces, graphics, design, compilation, information, computer code, products, software (including any downloadable software), or any music, images, video, text, services, and all other material or elements of or available through the Site provided by MusicPass ("Content") are protected by the copyright, trade dress, patent, and trademark laws of the United States and other countries, international conventions, and all other relevant intellectual property and proprietary rights, and applicable laws. Except for your User Submissions, all Content contained on the Site are the copyrighted property of MusicPass or its subsidiaries or affiliated companies and/or third-party licensors. All trademarks, service marks, and trade names are proprietary to MusicPass or its affiliates and/or third-party licensors whether registered or unregistered and may not be used in connection with any product or service or in any manner that is likely to cause confusion as to our endorsement, affiliation or sponsorship of any person, product or service. Except as expressly authorized by MusicPass, you agree not to sell, license, distribute, copy, modify, download, record, publicly perform or display, transmit, publish, edit, adapt, create derivative works from, or otherwise make unauthorized use of the Content and may only access the Content for your personal, non-commercial use. In the event that Content are downloaded to your computer or mobile phone, you do not obtain any ownership interest in such Content. All rights not expressly granted in these Terms are reserved.</p>
        <p className="description-without-margin">b) By installing, copying, or otherwise using the Site or its software, you acknowledge that you have read and understood these Terms, and agree to be bound by its terms and conditions. If you do not agree to (or cannot comply with) the terms and conditions of this Agreement, do not install, copy, or use the Site or Content.</p>
        <p className="description-without-margin">c) You agree that you will not, for any reason whatsoever, reverse engineer, decompile, disassemble, or otherwise tamper with any security components, usage rules or other protection measures applicable to the Site or Content. You agree to abide by the rules and policies established from time to time by MusicPass. Such rules and policies will be applied generally in a nondiscriminatory manner to users of the Site and software, and may include, for example, required or automated updates, modifications, and/or reinstallations of the software and obtaining available patches to address security, interoperability, and/or performance issues.</p>
        <p className="description-without-margin">You agree not to make any use of the Content that would infringe the copyright therein.</p>
        <p className="description-without-margin">d) The Site and any related software may enable you to obtain, listen to, view, and/or read (as the case may be) Content that may be obtained by you in digital form, and you shall do so solely for your individual, personal, noncommercial entertainment use.</p>
        <p className="description-without-margin">e) You agree not to share your MusicPass account with anyone other than yourself nor will you allow anyone other than yourself to access or use any Content accessible on or through the Site, including but not limited to sound recordings and/or musical compositions. You agree that you will not attempt to modify any software or Content obtained through the Site for any reason whatsoever, including for the purpose of disguising or changing any indications of the ownership or source of the Content. You further understand that you are not granted any commercial, sale, resale, reproduction, distribution, or promotional use rights for the Content, or any rights for uses that require a synchronization or public performance license with respect to the underlying musical composition and any unauthorized reproduction or distribution of Content is expressly prohibited and may violate applicable law. You are not permitted to modify, edit or repurpose any Content.</p>
        <p className="description-without-margin">f) You represent, warrant and agree that you are using the Site hereunder for your own personal, noncommercial entertainment use and not for redistribution or transfer of any kind. You agree (a) not to redistribute, broadcast, publicly perform or publicly display any Content, or otherwise transfer any Content obtained through the Site, (b) you will comply with all applicable laws in your use of the Content, (c) that you will remain a resident of the United States for the duration of your use of the Site.</p>
        <p className="description-without-margin">g) You understand and agree the Content may be owned by MusicPass or by third parties. However, in all circumstances, you understand and acknowledge that your rights with respect to Content will be limited by copyright law. All owners and providers of Content expressly reserve their rights in and to such Content and you are not permitted to infringe the rights of the copyright owner(s) of the Content, including but not limited to any sound recordings or musical compositions.</p>
        <p className="description-without-margin">h) MusicPass and/or the owners of the Content may, from time to time, remove Content from the Site without notice.</p>
        <p className="description-without-margin">i) The owners of Content are intended beneficiaries of this Agreement and shall have the right to enforce this Agreement against you.</p>
        <p className="description-without-margin">j) The Site, including all software, Content and other information, materials and products included on or otherwise made available to you through the Service are provided "as-is" and "as available" without warranties of any kind from MusicPass or any owners of Content. To the full extent permissible by applicable law, MusicPass and all owners of Content disclaim all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose. Neither MusicPass nor any owner of Content warrants that the Site or any software, Content, information, materials or products included on or otherwise made available to you through the Site are free of viruses or other harmful components.</p>
        <p className="description-without-margin">k) NEITHER MUSICPASS NOR ANY OWNER OF CONTENT WILL BE LIABLE FOR ANY INCIDENTAL, PUNITIVE, SPECIAL OR CONSEQUENTIAL DAMAGES OF ANY KIND ARISING FROM THE USE OF THE SITE OR FROM SOFTWARE, CONTENT, INFORMATION, MATERIALS OR PRODUCTS INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE SITE, OR FOR ANY DAMAGES IN EXCESS OF THE AMOUNT PAID FOR THE SPECIFIC ITEM OF CONTENT GIVING RISE TO THE APPLICABLE CLAIM FOR DAMAGES.</p>
        <p className="description-without-margin">10. Third-Party Sites, Products and Services; Links.</p>
        <p className="description-without-margin">The Site may include links or access to other web sites or services ("Linked Sites") solely as a convenience to users. MusicPass does not endorse any such Linked Sites, or the information, material, products, or services contained on other linked sites or accessible through other Linked Sites. Furthermore, MusicPass makes no express or implied warranties with regard to the information, material, products, or services that are contained on or accessible through linked sites. ACCESS AND USE OF LINKED SITES, INCLUDING THE INFORMATION, MATERIAL, CONTENT, PRODUCTS, AND SERVICES ON LINKED SITES OR AVAILABLE THROUGH LINKED SITES, IS SOLELY AT YOUR OWN RISK.</p>
        <p className="description-without-margin">Sometimes promotional plans are offered in conjunction with the provision of third party products and services. We are not responsible for the products and services provided by such third parties, and use of such products and services is at your own risk.</p>
        <p className="description-without-margin">Your correspondence or business dealings with, or participation in promotions of, third parties found on or through the Site are solely between you and such third party. YOU AGREE THAT MUSICPASS WILL NOT BE RESPONSIBLE OR LIABLE FOR ANY LOSS OR DAMAGE OF ANY SORT INCURRED AS THE RESULT OF ANY SUCH DEALINGS OR AS THE RESULT OF THE PRESENCE OF SUCH THIRD PARTIES ON THE SITE.</p>
        <p className="description-without-margin">11. Electronic Signatures and Agreements.</p>
        <p className="description-without-margin">You acknowledge and agree that by clicking on the button labeled "CONFIRM PURCHASE," "SUBMIT", "DOWNLOAD", "PLACE MY ORDER", "I ACCEPT" or such similar links as may be designated by MusicPass to accept the terms and conditions of these Terms, you are submitting a legally binding electronic signature and are entering into a legally binding contract. You acknowledge that your electronic submissions constitute your agreement and intent to be bound by these Terms. Pursuant to any applicable statutes, regulations, rules, ordinances or other laws, including without limitation the United States Electronic Signatures in Global and National Commerce Act, P.L. 106-229 (the "E-Sign Act") or other similar statutes, YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS AND OTHER RECORDS AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED THROUGH THE SITE OR SERVICES OFFERED BY MUSICPASS. Further, you hereby waive any rights or requirements under any statutes, regulations, rules, ordinances or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by other than electronic means.</p>
        <p className="description-without-margin">12. General Disclaimers; No Warranties.</p>
        <p className="description-without-margin">RESERVATIONS AND OTHER NON-MUSICPASS PRODUCTS AND SERVICES MADE AVAILABLE VIA THE SITE ARE PROVIDED BY THIRD PARTIES (AND THE DESCRIPTIONS OF THE FOREGOING POSTED ON THE SITE ARE PROVIDED BY SUCH THIRD PARTIES), NOT MUSICPASS. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, YOUR USE OF THE SITE AND YOUR ATTENDANCE AT, PARTICIPATION IN, PURCHASE AND/OR USE OF THE RESERVATIONS, IS SOLELY AT YOUR OWN RISK. WE DO NOT ASSUME ANY LIABILITY OR MAKE ANY WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, ARISING OUT OF, IN CONNECTION WITH OR WITH RESPECT TO THE SITE AND/OR RESERVATIONS.</p>
        <p className="description-without-margin">IN NO EVENT SHALL MUSICPASS BE LIABLE FOR ANY ACT, ERROR OR OMISSION BY ANY THIRD PARTY, INCLUDING, WITHOUT LIMITATION, ANY WHICH ARISES OUT OF OR IS ANY WAY CONNECTED WITH A USER’S ATTENDANCE, USE OF OR PARTICIPATION IN A EVENT OR PRODUCT, OR THE PERFORMANCE OR NON-PERFORMANCE OF ANY THIRD PARTY. MUSICPASS IS NOT AN AGENT OF ANY THIRD-PARTY.</p>
        <p className="description-without-margin">ALL ASPECTS OF OR CONTENT OR FEATURES AVAILABLE THROUGH THE SITE AND/OR RESERVATIONS ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, MUSICPASS, ON BEHALF OF ITSELF AND ITS SUPPLIERS AND PARTNERS, DISCLAIMS AND EXCLUDES ALL WARRANTIES, WHETHER STATUTORY, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS.</p>
        <p className="description-without-margin">WITHOUT LIMITING THE FOREGOING, MUSICPASS DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS (I) THAT THE SITE AND/OR ANY EVENT IS SUITABLE FOR YOU OR WILL MEET YOUR PERSONAL NEEDS, (II) REGARDING THE ADEQUACY OR SAFETY OF ANY EVENT OR RECOMMENDATION, (III) THAT THE SITE AND/OR ANY EVENT, OR ANY ASPECT THEREOF, WILL BE AVAILABLE OR PERMITTED IN YOUR JURISDICTION, (IV) THAT THE SITE, OR ANY ASPECT THEREOF, WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SITE AND ANY DOWNLOADABLE SOFTWARE, CONTENT, SERVICES, OR APPLICATIONS MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH THE SITE OR THE SERVER THAT MAKES THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR (V) REGARDING THE USE OF THE SITE AND ANY DOWNLOADABLE SOFTWARE, CONTENT, SERVICES, OR APPLICATIONS MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH THE SITE IN TERMS OF CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. ANY MATERIAL, CONTENT OR DATA THAT YOU DOWNLOAD OR OTHERWISE OBTAIN THROUGH THE SITE IS AT YOUR OWN RISK. YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGES TO YOUR COMPUTER SYSTEM OR LOSS OF DATA RESULTING FROM THE DOWNLOAD OF SUCH MATERIAL, CONTENT OR DATA.</p>
        <p className="description-without-margin">CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS SET FORTH IN THESE TERMS MIGHT NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS. TO THE EXTENT ANY DISCLAIMER OR LIMITATION OF LIABILITY DOES NOT APPLY, ALL APPLICABLE EXPRESS, IMPLIED, AND STATUTORY WARRANTIES WILL BE LIMITED IN DURATION TO A PERIOD OF 30 DAYS AFTER THE DATE ON WHICH YOU FIRST USED THE SITE, AND NO WARRANTIES SHALL APPLY AFTER SUCH PERIOD.</p>
        <p className="description-without-margin">13. Waiver and Release.</p>
        <p className="description-without-margin">YOU UNDERSTAND THAT MUSICPASS IS NOT A PLACE OF AMUSEMENT OR RECREATION, MUSIC VENUE, FACILITY, STUDIO OR SIMILAR ESTABLISHMENT AND THE RESERVATIONS THEY PROVIDE ARE OPERATED AND DELIVERED BY THE APPLICABLE VENUE AND NOT BY MUSICPASS. MUSICPASS IS NOT RESPONSIBLE FOR THE QUALITY OF ANY EVENT PROVIDED BY A VENUE OR THIRD PARTY (INCLUDING BUT NOT LIMITED TO THE FACILITY, ARTIST(S) OR SETUP). YOU ARE SOLELY RESPONSIBLE FOR DETERMINING WHETHER THE EVENT OR RECOMMENDATIONS AVAILABLE ON OR THROUGH THE SITE AND/OR RESERVATIONS ARE RIGHT FOR YOU.</p>
        <p className="description-without-margin">YOU UNDERSTAND THAT THERE ARE CERTAIN INHERENT RISKS AND DANGERS IN PARTICIPATING AND THAT THE RESERVATIONS YOU MAY ATTEND OR PARTICIPATE IN OFFER A RANGE OF ACTIVITY AND INTENSITY LEVELS. BY USING MUSICPASS (INCLUDING BUT NOT LIMITED TO ATTENDING, OR PARTICIPATING IN AN EVENT), YOU ACKNOWLEDGE AND AGREE, ON BEHALF OF YOURSELF, YOUR HEIRS, PERSONAL REPRESENTATIVES AND/OR ASSIGNS THAT YOU ARE AWARE OF THESE RISKS WHICH INCLUDE, BUT ARE NOT LIMITED TO, PROPERTY DAMAGE, ILLNESS, LOSS AND BODILY INJURY OR DEATH. YOU ACKNOWLEDGE THAT SOME OF THESE RISKS CANNOT BE ELIMINATED AND YOU SPECIFICALLY ASSUME THE RISK OF INJURY OR HARM.</p>
        <p className="description-without-margin">YOU ACKNOWLEDGE AND AGREE THAT IT IS YOUR RESPONSIBILITY TO CONSULT WITH YOUR PHYSICIAN OR OTHER HEALTH CARE PROFESSIONAL PRIOR TO USING MUSICPASS (INCLUDING BUT NOT LIMITED TO ATTENDING, OR PARTICIPATING IN AN EVENT) AND TO DETERMINE IF AND HOW PARTICIPATING IS APPROPRIATE FOR YOU. DO NOT USE RESERVATIONS IF YOUR PHYSICIAN OR HEALTH CARE PROVIDER ADVISES AGAINST IT. IF YOU EXPERIENCE FAINTNESS, DIZZINESS, PAIN OR SHORTNESS OF BREATH AT ANY TIME WHILE ATTENDING, YOU SHOULD STOP IMMEDIATELY.</p>
        <p className="description-without-margin">YOU ALSO UNDERSTAND AND AGREE THAT THE SITE OFFERS MUSIC AND DANCE-RELATED INFORMATION THAT IS DESIGNED FOR INFORMATIONAL, EDUCATIONAL AND ENTERTAINMENT PURPOSES ONLY. NOTHING STATED OR POSTED ON OR OTHERWISE AVAILABLE THROUGH ANY ASPECT OF THE SITE AND/OR AN EVENT IS INTENDED TO BE, AND MUST NOT BE TAKEN TO BE, THE PRACTICE OF MEDICAL, PROFESSIONAL OR COUNSELING CARE. YOU SHOULD NOT RELY ON ANY INFORMATION ON OR THROUGH THE SITE AND/OR AN EVENT AS A SUBSTITUTE FOR, NOR DOES IT REPLACE, PROFESSIONAL MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT. IF YOU HAVE ANY CONCERNS OR QUESTIONS ABOUT YOUR HEALTH OR FITNESS LEVEL, YOU SHOULD ALWAYS CONSULT A PHYSICIAN OR OTHER HEALTH-CARE PROFESSIONAL. DO NOT EVER DISREGARD, AVOID OR DELAY OBTAINING MEDICAL OR HEALTH RELATED ADVICE FROM YOUR HEALTH-CARE PROFESSIONAL BECAUSE OF SOMETHING YOU MAY HAVE READ OR HEARD ON OR THROUGH THE SITE AND/OR AN EVENT. THE USE OF ANY OF THE CONTENT, RECOMMENDATIONS AND INFORMATION PROVIDED ON OR THROUGH MUSICPASS IS SOLELY AT YOUR OWN RISK.</p>
        <p className="description-without-margin">THE SITE IS CONTINUALLY UNDER DEVELOPMENT AND MUSICPASS MAKES NO WARRANTY OF ANY KIND, IMPLIED OR EXPRESS, AS TO ITS ACCURACY, COMPLETENESS OR APPROPRIATENESS FOR ANY PURPOSE. IN THAT REGARD, DEVELOPMENTS IN RESEARCH MAY IMPACT THE FITNESS OR RELATED ADVICE THAT APPEARS ON OR IN CONNECTION WITH THE SITE. NO ASSURANCE CAN BE GIVEN THAT THE ADVICE OR RECOMMENDATIONS CONTAINED IN OR THROUGH THE SITE AND/OR AN EVENT WILL ALWAYS INCLUDE THE MOST RECENT FINDINGS OR DEVELOPMENTS WITH RESPECT TO THE PARTICULAR MATERIAL OR CONTENT.</p>
        <p className="description-without-margin">THEREFORE, TO THE FULLEST EXTENT PERMITTED BY LAW, YOU RELEASE, INDEMNIFY, AND HOLD HARMLESS MUSICPASS, ITS PARENT, SUBSIDIARIES OR AFFILIATED ENTITIES, AND EACH OF THEIR RESPECTIVE OFFICERS, DIRECTORS, MEMBERS, EMPLOYEES, CONSULTANTS, CONTRACT EMPLOYEES, REPRESENTATIVES AND AGENTS, AND EACH OF THEIR RESPECTIVE SUCCESSORS AND ASSIGNS, FROM ANY AND ALL RESPONSIBILITY, CLAIMS, ACTIONS, SUITS, PROCEDURES, COSTS, EXPENSES, DAMAGES AND LIABILITIES ARISING OUT OF OR IN ANY WAY RELATED TO YOUR PARTICIPATION IN OR USE OF THE SITE AND/OR ATTENDANCE AT, PARTICIPATION IN, PURCHASE OF AND/OR USE OF ANY EVENT) INCLUDING BUT NOT LIMITED TO WITH RESPECT TO BODILY INJURY, PHYSICAL HARM, LOSS, ILLNESS, DEATH OR PROPERTY DAMAGE.</p>
        <p className="description-without-margin">14. Indemnification; Hold Harmless.</p>
        <p className="description-without-margin">You agree to indemnify and hold MusicPass, its affiliated entities, subsidiaries, its suppliers, service providers and partners and each of their respective officers, directors, members, employees, consultants, contract employees, representatives and agents, and each of their respective successors and assigns, harmless from any claims, actions, suits, costs, expenses, losses, damages, liabilities, including attorneys’ fees, arising out of or in connection with your misuse of the Site, Reservations, violation of these Terms, violation of the rights of any other person or entity, or any breach of your representations, warranties, and covenants set forth in these Terms.</p>
        <p className="description-without-margin">15. Limitation of Liability and Damages.</p>
        <p className="description-without-margin">UNDER NO CIRCUMSTANCES WILL MUSICPASS OR ITS AFFILIATES, CONTRACTORS, EMPLOYEES, AGENTS, OR THIRD-PARTY PARTNERS OR SUPPLIERS BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES UNDER ANY THEORY OF LIABILITY, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE AND PRODUCT LIABILITY), OR OTHERWISE, EVEN IF MUSICPASS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN SUCH CASES, MUSICPASS’S LIABILITY WILL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.</p>
        <p className="description-without-margin">MUSICPASS’ LIABILITY TO YOU IS LIMITED TO $50 OR THE AMOUNTS, IF ANY, PAID BY YOU TO MUSICPASS UNDER THIS AGREEMENT IN THE THREE MONTHS IMMEDIATELY PRIOR TO THE EVENT FIRST GIVING RISE TO THE CLAIM, WHICHEVER IS MORE. THE FOREGOING LIMITATIONS WILL APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, REGARDLESS OF WHETHER MUSICPASS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND REGARDLESS OF WHETHER ANY REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
        <p className="description-without-margin">16. Venue Waivers and Terms.</p>
        <p className="description-without-margin">Members taking Reservations are deemed to agree to the liability waivers and terms of individual Venues. Your participation in any Event may be subject to addition policies, rules or conditions of the applicable Venue and you understand and agree that you may not be permitted to reserve or attend reservations or services if you do not comply with these Terms or the policies of the Venues or as otherwise determined by a Venue. If you have questions about a Venue’s waiver or other terms, please see the applicable Venue’s website or contact the Venue directly.</p>
        <p className="description-without-margin">17. Infringement Policy.</p>
        <p className="description-without-margin">Please see our <span><a href={"/dcma"}>Digital Millennium Copyright Act (DMCA) document</a></span> for an explanation of our copyright and trademark policies.</p>
        <p className="description-without-margin">18. Arbitration Agreement</p>
        <p className="description-without-margin">PLEASE READ THE FOLLOWING CAREFULLY:</p>
        <p className="description-without-margin">a) Purpose. This Arbitration Agreement facilitates the prompt and efficient resolution of any disputes that may arise between you and MusicPass. Arbitration is a form of private dispute resolution in which parties to a contract agree to submit their disputes and potential disputes to a neutral third person (called an arbitrator) for a binding decision, instead of having such dispute(s) decided in a lawsuit, in court, by a judge or jury trial.</p>
        <p className="description-without-margin">Please read this Arbitration Agreement carefully. It provides that all disputes between you and MusicPass shall be resolved by binding arbitration. Arbitration replaces the right to go to court. In the absence of this arbitration agreement, you may otherwise have a right or opportunity to bring claims in a court, before a judge or jury, and/or to participate in or be represented in a case filed in court by others (including, but not limited to, event actions). Entering into this Arbitration Agreement constitutes a waiver of your right to litigate claims in court and all opportunity to be heard by a judge or jury. There is no judge or jury in arbitration, and court review of an arbitration award is limited. The arbitrator must follow this Arbitration Agreement and can award the same damages and relief as a court (including attorney’s fees).</p>
        <p className="description-without-margin">For the purpose of this Arbitration Agreement, "MusicPass" means MusicPass and its parents, subsidiaries, and affiliated companies, and each of their respective officers, directors, employees, and agents. The term "Dispute" means any dispute, claim, or controversy between you and MusicPass regarding any aspect of your relationship with MusicPass, whether based in contract, statute, regulation, ordinance, tort (including, but not limited to, fraud, misrepresentation, fraudulent inducement, negligence, gross negligence or reckless behavior), or any other legal or equitable theory, and includes the validity, enforceability or scope of this Arbitration Agreement (with the exception of the enforceability of the Event Action Waiver clause below). "Dispute" is to be given the broadest possible meaning that will be enforced.</p>
        <p className="description-without-margin">WE EACH AGREE THAT, EXCEPT AS PROVIDED BELOW, ANY AND ALL DISPUTES, AS DEFINED ABOVE, WHETHER PRESENTLY IN EXISTENCE OR BASED ON ACTS OR OMISSIONS IN THE PAST OR IN THE FUTURE, WILL BE RESOLVED EXCLUSIVELY AND FINALLY BY BINDING ARBITRATION RATHER THAN IN COURT IN ACCORDANCE WITH THIS ARBITRATION AGREEMENT.</p>
        <p className="description-without-margin">b) Pre-Arbitration Dispute Resolution. Before initiating any Dispute, whether in court or arbitration, you must first give MusicPass an opportunity to resolve the Dispute by mailing written notification to MusicPass, Legal Department, 4000 Ponce De Leon Blvd., Ste 470, Coral Gables, FL 33146. That written notification must include (1) your name, (2) your address, (3) a written description of the Dispute, and (4) a description of the specific relief you seek. If MusicPass does not resolve the Dispute to your satisfaction within 45 days after it receives your written notification, you may pursue your Dispute in arbitration.</p>
        <p className="description-without-margin">c) Arbitration Procedures. If the Dispute is not resolved as provided above in the Pre-Arbitration Claim Resolution section, either you or MusicPass may initiate arbitration proceedings. The American Arbitration Association ("AAA"), www.adr.org, or JAMS, www.jamsadr.com, will arbitrate all Disputes, and the arbitration will be conducted before a single arbitrator. The arbitration shall be commenced as an individual arbitration, and shall in no event be commenced as a class arbitration. All issues shall be for the arbitrator to decide, including the scope of this Arbitration Agreement. For arbitration before the AAA, for Disputes in which less than $75,000 is at issue, the AAA’s Supplementary Procedures for Consumer-Related Disputes will apply; for Disputes involving $75,000 or more, the AAA’s Commercial Arbitration Rules will apply. In either instance, the AAA’s Optional Rules For Emergency Measures Of Protection shall apply. The AAA rules are available at www.adr.org or by calling 1-800-778-7879. For arbitration before JAMS, the JAMS Comprehensive Arbitration Rules & Procedures and the JAMS Recommended Arbitration Discovery Protocols For Domestic, Commercial Cases will apply. The JAMS rules are available at www.jamsadr.com or by calling 1-800-352-5267. In the event that this Arbitration Agreement conflicts with the applicable arbitration rules, this Arbitration Agreement shall govern. Under no circumstances will event action procedures or rules apply to the arbitration. Because your contract with MusicPass, the Terms of Use, and this this Arbitration Agreement concern interstate commerce, the Federal Arbitration Act ("FAA") governs the arbitrability of all Disputes. However, the arbitrator will apply applicable substantive law consistent with the FAA and the applicable statute of limitations or condition precedent to suit.</p>
        <p className="description-without-margin">d) Arbitration Award. The arbitrator may award on an individual basis any relief that would be available pursuant to applicable law, and will not have the power to award relief to, against or for the benefit of any person who is not a party to the proceeding. The arbitrator shall make any award in writing but need not provide a statement of reasons unless requested by a party. Such award by the arbitrator will be final and binding on the parties, except for any right of appeal provided by applicable federal law, including but not limited to the Federal Arbitration Act ("the FAA"), and may be entered in any court having jurisdiction over the parties for purposes of enforcement.</p>
        <p className="description-without-margin">e) Location of Arbitration. Arbitration shall take place in Miami-Dade County, Florida, but it may proceed by telephone if you so choose.</p>
        <p className="description-without-margin">f) Payment of Arbitration Fees and Costs. MusicPass will pay all arbitration filing fees and arbitrator’s costs and expenses upon your written request given prior to the commencement of the arbitration. You are responsible for all additional fees and costs that you incur in the arbitration, including, but not limited to, attorneys or expert witnesses. Fees and costs may be awarded as provided pursuant to applicable law.</p>
        <p className="description-without-margin">g) Event Action Waiver. Any Disputes arising out of or relating to your use of the Site and/or attendance at, participation in or use of Reservations, any purchase you make on or through the Site, any information you provide via the Site, and/or these Terms (including the formation, performance, or alleged breach), shall be submitted individually by you and will not be subject to any event action or representative status. The arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a event or representative proceeding or claims (such as a class action, representative action, consolidated action or private attorney general action). Neither you, nor any other Member of MusicPass and/or user of MusicPass services, can be a class representative, event member, or otherwise participate in a class, representative, consolidated or private attorney general proceeding with respect to the matters set forth in the first sentence of this paragraph. You agree that this Event Action Waiver is material and essential to the arbitration of any dispute between you and MusicPass and is non-severable from the Arbitration Agreement. If any portion of this Event Action Waiver is limited, voided, or cannot be enforced, then the Arbitration Agreement shall be null and void. You understand that by agreeing to this Event Action Waiver, you may only pursue Dispute against MusicPass in an individual capacity and not as a plaintiff or event member in any purported event action or representative proceeding.</p>
        <p className="description-without-margin">h) Limitation of Procedural Rights. You understand and agree that, by entering into this Arbitration Agreement, you and MusicPass are each agreeing to arbitration instead of the right to a trial before a judge or jury in a public court. In the absence of this Arbitration Agreement, you and MusicPass might otherwise have a right or opportunity to bring Disputes in a court, before a judge or jury, and/or to participate or be represented in a case filed in court by others (including event actions). By using the MusicPass Site or any Event, product or services, or otherwise accepting these Terms, you are entering into this Arbitration Agreement, and you give up those procedural rights. Other rights that you would have if you went to court, such as the right to appeal and to certain types of discovery, may be more limited in arbitration. The right to appellate review of an arbitrator’s decision is much more limited than in court, and in general an arbitrator’s decision may not be appealed for errors of fact or law.</p>
        <p className="description-without-margin">i) Severability. If any clause within this Arbitration Agreement, other than the Event Action Waiver clause above, is found to be illegal or unenforceable, that clause will be severed from this Arbitration Agreement, and the remainder of this Arbitration Agreement will be given full force and effect. If the Event Action Waiver clause is found to be illegal or unenforceable, then this entire Arbitration Agreement will be unenforceable and the Dispute will be decided by a court of competent jurisdiction.</p>
        <p className="description-without-margin">j) Continuation. This Arbitration Agreement shall survive the termination of your contract with MusicPass and your use of the MusicPass Site, Reservations and services.</p>
        <p className="description-without-margin">19. Miscellaneous.</p>
        <p className="description-without-margin">a) Choice of Law; Forum. These Terms shall be governed in all respects by the laws of the State of New York, without regard to conflict of law provisions, consistent with the Federal Arbitration Act (to the extent permitted by applicable law). If for any reason a claim proceeds in court rather than in arbitration (including any claims brought by parties outside the United States), the dispute shall be exclusively brought in state or federal court located in Miami, Florida.</p>
        <p className="description-without-margin">b) Assignment. We may assign our rights and obligations under these Terms. The Terms will inure to the benefit of our successors, assigns and licensees.</p>
        <p className="description-without-margin">c) Severability. If any provision of these Terms shall be unlawful, void, or for any reason unenforceable, then that provision will be deemed severable from these Terms and will not affect the validity and enforceability of any remaining provisions.</p>
        <p className="description-without-margin">d) Headings. The heading references herein are for convenience purposes only, do not constitute a part of these Terms, and will not be deemed to limit or affect any of the provisions hereof.</p>
        <p className="description-without-margin">e) Entire Agreement. These Terms and any applicable Additional Terms, as each may be amended as set forth herein, are the entire agreement between you and MusicPass relating to the subject matter herein.</p>
        <p className="description-without-margin">f) Claims; Statute of Limitations. IN THE EVENT YOU HAVE A CAUSE OF ACTION THAT IS NOT OTHERWISE BARRED BY THESE TERMS, YOU AND MUSICPASS AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THESE TERMS AND/OR THE SITE AND/OR ATTENDANCE AT, PARTICIPATION IN, USE OF OR PURCHASE OF RESERVATIONS) MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</p>
        <p className="description-without-margin">g) Disclosures. The services hereunder are offered by MusicPass LLC, located at: 4000 Ponce De Leon Blvd, Ste 470, Coral Gables, FL 33146. Contact us here. If you are a California resident, you may have this same information emailed to you by sending a letter to the foregoing address with your email address and a request for this information.</p>
        <p className="description-without-margin">h) Waiver. No waiver of any of these Terms by MusicPass is binding unless authorized in writing by an executive officer of MusicPass. In the event that MusicPass waives a breach of any provision of these Terms, such waiver will not be construed as a continuing waiver of other breaches of the same nature or other provisions of these Terms and will in no manner affect the right of MusicPass to enforce the same at a later time. Further, in the event we choose to grant an exception to these Terms, any such exception is in our sole discretion and does not entitle you or anyone else to any exceptions in the future for similar circumstances.</p>
        <p className="description-without-margin">i) Notice. Except as explicitly stated otherwise, legal notices will be served, with respect to MusicPass, on MusicPass’ national registered agent, and, with respect to you, to the email address you provide to MusicPass during the registration process. Notice will be deemed given 24 hours after email is sent, unless the sending party is notified that the email address is invalid. Alternatively, we may give you legal notice by mail to the address provided during the registration process. In such case, notice will be deemed given three days after the date of mailing.</p>
    </>;

    return (
        <TermsOfUseStyle>
            <HeadingWithContentStyle>
                <Link to="/">
                    <div className="button-wrapper" onClick={(e)=>history.goBack()}>
                        <LeftChevronIcon/> Back To Previous Page
                    </div>
                </Link>

                <h2 className="heading">{"Customer Terms of Use"}</h2>
                {content}
            </HeadingWithContentStyle>
        </TermsOfUseStyle>
    );
}
