import React from "react";
import {PartnerTermsStyle} from "./partner-terms.style";
import {useHistory} from "react-router";
import {HeadingWithContentStyle} from "../../components/HeadingWithContent/HeadingWithContent.style";
import {Link} from "react-router-dom";
import {LeftChevronIcon} from "../../assets";

export default function PartnerTermsAndCondition() {
    const history = useHistory();

    const content=<>
        <p className="description-without-margin" style={{marginTop:-20}}>(last updated October 19, 2022)</p>
        <p className="description-without-margin">MusicPass, Inc. (“<span style={{fontWeight:""}}>MusicPass</span>,” “<span style={{fontWeight:""}}>we</span>” or “<span style={{fontWeight:""}}>us</span>”) is pleased to include you in our roster of Partners on the MusicPass™ website at <a href={"https://musicpassonline.com"} target={"_black"}>www.musicpassonline.com</a> (together with any iPhone®, Android® or other mobile application of such website, our “<span style={{fontWeight:""}}>Website</span>”). Please read these Terms and Conditions (the “<span style={{fontWeight:""}}>Terms</span>”), and let us know if you have any questions. These Terms are incorporated into the Partner Agreement (if any) and any other agreement between Partner (“<span style={{fontWeight:""}}>Partner</span>” or “<span style={{fontWeight:""}}>you</span>”) and MusicPass (collectively, this “<span style={{fontWeight:""}}>Agreement</span>”). Additionally, as part of the on-boarding process, you may be required to complete a worksheet and information from the worksheet may be incorporated herein by reference. By signing the Partner Agreement or otherwise accepting these Terms, you agree to be bound by these Terms, which apply to all locations, events, and services you make available via the MusicPass platform, unless otherwise communicated or agreed upon by MusicPass. You understand and agree that the Partner Agreement and these Terms may be updated or amended by MusicPass from time to time as set forth in the Miscellaneous Section below.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>1. ACCOUNT SET-UP & DOCUMENTATION.</span></p>
        <p className="description-without-margin" >1.	<span style={{marginLeft:"50px"}}>Bank Account Information. As part of the on-boarding process, you will be given access to our on-line payment system to provide your bank account information (“<span style={{fontWeight:""}}>Bank Account</span>”). Once your Bank Account has been verified, we will make payments to you hereunder by electronic transfer to your Bank Account via the Automated Clearing House (ACH). Until your Bank Account has been verified, we will send payments to you hereunder by check. You are responsible for updating our on-line payment system as to any changes in your Bank Account.</span></p>
        <p className="description-without-margin">2.	<span style={{marginLeft:"50px"}}>IRS Form W-9. Within 14 days of the date you sign the Partner Agreement, you will provide MusicPass with a completed/signed IRS Form W-9. We may withhold applicable amounts from payments due to you hereunder until such time as we have received this completed/signed form.</span></p>
        <p className="description-without-margin">3.	<span style={{marginLeft:"50px"}}>Availability. Your events or other services will be available for use by MusicPass members after you are launched on our Website. We reserve the right to limit the inventory or number of spots available. Partner shall accord the same preferences and priorities to reservations made via MusicPass as reservations made by Partner's clients/members. In addition, Partner shall not cancel a MusicPass reservation except where the event or service itself has been cancelled. We continually update and test various aspects of the MusicPass platform and may include or exclude you from these tests.</span></p>
        <p className="description-without-margin">4.	<span style={{marginLeft:"50px"}}>Partner’s MusicPass Page. We will send you a link to review your page on our Website. The MusicPass design team may review that all photos and design comply with MusicPass brand requirements.</span></p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>2. PAYMENTS, EXCLUSIVITY & REPORTING.</span></p>
        <p className="description-without-margin">1.	<span style={{marginLeft:"50px"}}>Payments for Qualifying Events. As full and complete payment for all goods and services you provide to us hereunder, MusicPass will pay you the applicable rate(s) as set forth in the Partner Agreement for each Qualifying Attendance. A “<span style={{fontWeight:""}}>Qualifying Attendance</span>” means a reservation for an event or service at Partner booked through our Website or by MusicPass unless such reservation (1) was cancelled by MusicPass or the MusicPass member in accordance with your cancellation policy, up to 24 hours in advance, (provided that if a reservation is cancelled late, but is subsequently rebooked via MusicPass, then such late cancellation shall not count as a Qualifying Attendance); (2) was cancelled by you; or (3) otherwise was not honored by you. For the avoidance of doubt, attendances that are not booked by us or through our platform, such as last-minute walk-ins, do not count as Qualifying Attendance. MusicPass may review Partner's rate from time to time to verify Partner pricing and ensure Partner’s rate is not price gouging and remains in line with Partner’s other packages and pricing. We will communicate any cost that may apply to your use of any upgrades, products, services or features we may release from time to time.</span></p>
        <p className="description-without-margin">2.	<span style={{marginLeft:"50px"}}>Exclusivity. You agree not to participate in or launch any other services or arrangements (whether direct-to-consumer or business-to-business) that are similar in form and substance to those, which you are agreeing to with us pursuant to this Agreement (e.g., variety package deal, alternative music event Partner subscription offerings, multi-Partner package programs). However, nothing in the prior sentence shall be interpreted as restricting your ability to run promotions on a “deal site” where access to your events are sold directly to the consumer at a discount.</span></p>
        <p className="description-without-margin">3.	<span style={{marginLeft:"50px"}}>Reports & Payment Date. Payments for Qualifying Attendances will be paid to you periodically (but in no case later than 15 business days after the last day of the month). Payments for Qualifying Attendances are calculated by data contained in the Partner dashboard and as such will be the final determinant of payment. You may reconcile the data in the Partner dashboard to our payment and must bring to our attention any discrepancies within 30 days after the last day of the month in which there is a discrepancy.</span></p>
        <p className="description-without-margin">4.	<span style={{marginLeft:"50px"}}>Reconciliation. We have 90 days after each payment to you to make reconciliation adjustments, such as in respect of events that were cancelled but as to which we have remitted payment. We may credit overpayments against any other payments due to you hereunder. In addition, you agree to provide us reasonable access during business hours to your books and records to confirm that our payments to you hereunder are correct.</span></p>
        <p className="description-without-margin">5.	<span style={{marginLeft:"50px"}}>Banking Authorization. You hereby acknowledge that our origination of all ACH transactions to your Bank Account must comply with provisions of U.S. law. Please note that ACH payments may take up to five (5) business days to become available in your Bank Account after processing.</span></p>
        <p className="description-without-margin">6.	<span style={{marginLeft:"50px"}}>Fraud. In no event will Partner be entitled to earn payments for (and if paid, MusicPass will be entitled to reimbursement for) standard reservations, Digital Content reservations, user purchases, or for anything else in cases of Partner’s fraud, bad faith, or other misconduct (including for reservations booked using a MusicPass free or discounted trial by any Person Partner inappropriately encouraged or incentivized or by Partner’s employees, staff, contractors, agents, family members, or friends, or otherwise made illegitimately in connection with fraud, bad faith, or in violation of MusicPass’ user terms) in MusicPass’ determination.</span></p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>3. MEMBER VISITS; FEES PAYABLE BY MEMBERS.</span></p>
        <p className="description-without-margin">Except as provided in the next sentence, you agree not to charge MusicPass members for any fees associated with attending events and services booked through our Website or by MusicPass. Partner may not charge MusicPass members any fee that is not being charged to Partner’s existing and regular clients. We reserve the right to credit our members for any fees improperly assessed against them and then to apply such credits against payments otherwise due to you hereunder. In addition, MusicPass has no responsibility for any payments that may be due to you from our members.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>4. TAXES.</span></p>
        <p className="description-without-margin">You are solely responsible for collecting/remitting local or state tax authorities any applicable taxes related to transactions herein.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>5. CUSTOMER DATA.</span></p>
        <p className="description-without-margin">1.	Use of Customer Data. If you have gained access to any Customer Data in connection with MusicPass, such as through an integration with the Website, you agree not to process or use such Customer Data for any purpose other than booking MusicPass reservations in accordance with any documented instructions of MusicPass (“<span style={{fontWeight:""}}>Permitted Purpose</span>”). For clarity, you must not use it for any other purpose, including but not limited to: (i) marketing or sending communications via mail, email, or phone; (ii) analytics, and/or (iii) selling, disclosing or otherwise communicating Customer Data to any third party for monetary or other valuable consideration, and you agree to implement reasonable security procedures and practices to protect Customer Data from such unauthorized use, as well as from other unauthorized access, disclosure, use, loss, alteration, exfiltration, theft, and accidental or unlawful destruction (“<span style={{fontWeight:""}}>Security Incident</span>”). To use Customer Data for any purpose other than the Permitted Purpose, you must independently obtain consent directly from the customers, and you must comply with applicable privacy and data protection laws. You are solely and exclusively responsible for ensuring that your collection, processing, and use of Customer Data complies with all requirements of applicable law and will be independently responsible under such law for any failures to do so. Nothing in the foregoing is intended to restrict your use of data that you collect independently and directly from a customer (rather than through MusicPass or an integration with MusicPass) in compliance with applicable law. “<span style={{fontWeight:""}}>Customer Data</span>” means any data which relates to, describes, is capable of being associated with, or could reasonably be linked, directly or indirectly, with a former, current, or potential MusicPass customer, or any information that may be derived from such data, including customer’s name, home, business or other physical address, email address, phone number, birthdate, information about event participation, customer tendencies, and financial transaction data.</p>
        <p className="description-without-margin">2.	Security. Upon becoming aware of any actual or suspected Security Incident relating to Customer Data or other MusicPass confidential information, you shall: (i) inform MusicPass immediately;, (take all such measures and actions as are necessary to remedy or mitigate the effects of the Security Incident, take all actions necessary to comply with applicable data protection law, and keep MusicPass informed of all developments in connection with the Security Incident. You agree to cooperate with any investigation by MusicPass, assist in mitigating damages, and bear expenses that MusicPass incurs to comply with applicable laws arising from any Security Incident relating to Customer Data or other confidential information. You agree to remain fully liable for any breach of this Section 5 and/or applicable data protection law that is caused by an act or omission of your employees, agents, and/or third parties that gain access to Customer Data through you.</p>
        <p className="description-without-margin">3.	Targeting. You agree not to (i) target or offer promotions to MusicPass customers (such as by sending emails) unless such promotions are also available in the same manner and to the same extent as they are available to all of your direct customers, (ii) make any comparative references to MusicPass, its services or pricing, and/or other partners’ or users’ participation in MusicPass, and/or (iii) undercut MusicPass pricing.</p>
        <p className="description-without-margin">4.	Further Documentation and Cooperation. You agree to execute any additional documentation and take any other further action that is or may become necessary to comply with applicable data protection law. You further agree to reasonably cooperate with MusicPass in this regard if MusicPass seeks your assistance.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>6. TERM AND TERMINATION.</span></p>
        <p className="description-without-margin">This Agreement will have an initial term of one year and will automatically renew for additional one‐year terms until such time as this Agreement is terminated. Partner may terminate this Agreement for any reason upon 90 days advance notice. MusicPass may terminate this Agreement for any reason upon 30 days advance notice. During the period between the notice of termination and the effective date of termination, Partner (1) shall maintain, and not restrict, MusicPass access to Partner's reservation software and (2) shall not reduce the percentage of its inventory made available to MusicPass by more than 50%. In addition, MusicPass may terminate this Agreement or suspend your participation in the MusicPass network if you breach this Agreement, due to quality issues, or in MusicPass' discretion in the event of a force majeure occurrence or an occurrence beyond MusicPass' control. Sections 2(d), 2(e), 3, 4, 5, 7, 10, 11, 12, 13, 14 and this Section 6 will continue in full force and effect after any termination of this Agreement.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>7. INTELLECTUAL PROPERTY RIGHTS</span></p>
        <p className="description-without-margin">1.	Partner IP. During the term of this Agreement, and solely in connection with our promotion of your goods and services and MusicPass, you grant MusicPass a non-exclusive, worldwide, royalty free, paid‐up, right to use, modify, reproduce, publicly display, bid on, distribute, broadcast, transmit, stream, publish and publicly perform Partner IP and 3rd Party IP, in each case in all media or formats now known or hereinafter developed (the “<span style={{fontWeight:""}}>License</span>”), including without limitation for your Partner page, blog posts, emails, banner ads, search engine marketing. While MusicPass’ use of the Partner IP or 3rd Party IP as contemplated by this License shall be within our discretion, you expressly retain the right to request that we use Partner IP or 3rd Party IP pursuant to any written guidelines that you provide to us. After any termination of this Agreement, we will use commercially reasonable efforts to remove Partner IP and 3rd Party IP from our Website and other marketing materials; however, we will be authorized to maintain Partner IP and 3rd Party IP to the extent reflected in blog entries, cached pages or in marketing materials where more than one Partner is referenced or which otherwise would not be commercially feasible for MusicPass to remove and/or modify.</p>
        <p className="description-without-margin">2.	MusicPass IP. During the term of this Agreement, you may use the MusicPass name, logo and other MusicPass IP specified by us in writing in select locations (e.g., on Partner’s website, at check in) solely <span style={{background:""}}>in accordance with any marketing guidelines that we provide to you</span> and subject to our right to withdraw or limit such permission at any time. Without our express written authorization (from an executive officer), you shall not otherwise use MusicPass IP for any purpose. You agree not to disparage or otherwise denigrate MusicPass and not to promote a competitive offering.</p>
        <p className="description-without-margin">3.	All rights to Partner IP and 3rd Party IP not expressly granted in this Agreement to us are reserved by you, and all rights to MusicPass IP not expressly granted in this Agreement to you are reserved by us.</p>
        <p className="description-without-margin">4.	You shall not prepare any derivative work based on the MusicPass IP or translate, reverse engineer, decompile or disassemble the MusicPass IP. You acknowledge and agree that, as between the parties, MusicPass owns all interest in and to MusicPass IP. You further agree not to take any action to challenge or object to the validity of MusicPass’s rights in the MusicPass IP or MusicPass’ ownership or registration thereof.</p>
        <p className="description-without-margin">5.	If you provide us with Feedback, you assign and agree to assign to MusicPass and its affiliates all right, title, and interest in and to any intellectual property rights associated with such Feedback. You agree to provide MusicPass such assistance as MusicPass may reasonably require to document, perfect, or maintain MusicPass’s rights in and to the Feedback.</p>
        <p className="description-without-margin">6.	MusicPass shall have no liability to you, your employees, contractors, agents and its or their affiliates in respect of any reviews or comments posted by our members on our Website or otherwise.</p>
        <p className="description-without-margin">7.	Definitions. As used in this Agreement, “<span style={{fontWeight:""}}>MusicPass IP</span>” means any intellectual property associated with our Website, Customer Data, MusicPass trade names, logos, trademarks, domain names, social media identifiers, all data collected through or from our Website, all audiovisual content, video or audio recordings, photographs, graphics, artwork, text or any other content created by MusicPass or at MusicPass’ direction, or assigned to MusicPass, and any materials, software, technology or tools used or provided by MusicPass to promote the goods and services and conduct its business in connection therewith; “<span style={{fontWeight:""}}>Feedback</span>” means feedback, suggestions, reviews, modifications, data, images, text, or other information or content about our products or services or otherwise in connection with this Agreement, any MusicPass IP, or your participation in this Agreement; “<span style={{fontWeight:""}}>Partner IP</span>” means Partner’s name, logos, trademarks, service marks, domain names, and any audiovisual content, video or recordings, photographs, graphics, artwork, text and any other content provided, specified, recommended, directed, authorized or approved for use by Partner including Digital Content (as defined below) and Feedback; and “<span style={{fontWeight:""}}>3rd Party IP</span>” means any third party’s name, logos, trademarks, service marks, domain names, audiovisual recordings, video or recordings, photographs, graphics, artwork, text and any other content provided, specified, recommended, directed, authorized or approved for use by Partner.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>8. REPRESENTATIONS.</span></p>
        <p className="description-without-margin">You represent and warrant that:</p>
        <p className="description-without-margin">1.	you have the right, power and authority to enter into this Agreement;</p>
        <p className="description-without-margin">2.	you are registered, to the extent required by applicable law, for sales and use tax collection purposes in all jurisdictions where the goods and/or services you make available to the MusicPass platform will be provided;</p>
        <p className="description-without-margin">3.	you own all interest in and to the Partner IP and Feedback and have the right to grant us the License;</p>
        <p className="description-without-margin">4.	the Partner IP, 3rd Party IP and your goods and services (including the goods/services you make available to the MusicPass platform) do not include any material that gives rise to civil liability or otherwise violates any law;</p>
        <p className="description-without-margin">5.	you and your employees, contractors and agents have had proper education and training and hold all required and up-to-date regulatory authorizations, licenses and certifications relating to any goods or services described in this Agreement;</p>
        <p className="description-without-margin">6.	you comply with all laws and regulations applicable to your business (including business licenses, insurance documents, etc.); and</p>
        <p className="description-without-margin">7.	your business information and Bank Account as provided pursuant to this Agreement are accurate and you are the authorized person to receive the funds sent by MusicPass.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>9. INSURANCE.</span></p>
        <p className="description-without-margin">At your sole cost and expense, you shall have and maintain in force at least the following insurance coverage:</p>
        <p className="description-without-margin">Solely to the extent required by applicable law, <span style={{fontWeight:"bold"}}>Worker’s Compensation Insurance</span>, including occupational illness or disease coverage, or other similar social insurance with a minimum limit of $100,000 per occurrence, accident or disease and $500,000 in the aggregate; and <span style={{fontWeight:"bold"}}>Commercial General Liability Insurance</span>, including products, completed operations liability and personal injury, contractual liability and broad form property damage liability coverage for damages to any property with a minimum combined single limit of $1 million per occurrence and $2 million in the aggregate. Except as to any required Worker's Compensation Insurance, the foregoing insurance coverage will be primary and non‐contributing with respect to any other insurance or self-insurance that may be maintained by any other party. Upon our request, you shall arrange for your insurers to issue certificates of insurance issued by an authorized representative of the insurer evidencing that the coverage and policy endorsements required pursuant to these Terms are maintained in force and that MusicPass is named (endorsed) as an Additional Insured under all such policies (except as to Workers Compensation Insurance). The insurers selected by you each will have an A.M. Best & Co. rating of not less than A- or otherwise be acceptable to the MusicPass.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>10. REMEDIES.</span></p>
        <p className="description-without-margin">We agree to indemnify you and hold you harmless for any breach by us of our obligations under this Agreement. You are solely responsible for, and to the maximum extent allowed under applicable law, shall indemnify, release, defend and hold MusicPass, its affiliated and related entities, and any of its respective officers, directors, agents and employees, harmless from and against any Losses arising out of or relating to any of the following: (a) any breach by you of this Agreement, or of your representations and warranties hereunder (including misuse of Customer Data); (b) your sales, use, or similar state or local tax obligations arising in connection with this Agreement; (c) claims arising out of or relating to goods and services provided by Partner or any of its affiliates, or as to any of its or their facilities, including but not limited to, any claims for false advertising, personal injury, death, or property damages. We maintain the right to control our own defense and to choose and appoint our own defense counsel, regardless of the presence or absence of a conflict of interest between the parties. Your duty to defend us includes the duty to pay our reasonable defense fees and costs. In addition to any other rights or remedies set forth herein, we may offset any amounts due or payable by you pursuant to this Agreement against any amounts due or payable by us pursuant to this Agreement.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>11. CONFIDENTIALITY.</span></p>
        <p className="description-without-margin">You agree not to disclose the terms described in this Agreement or any non-public information that we may share with you from time to time (such as business or product development plans) to any party (other than your employees, parent entity, shareholders, attorneys and accountants on a strict need-to-know basis, provided that you have taken reasonable precautions to preserve the confidentiality of the information made available to such parties). In the event of a breach of Section 5 or this Section 11, we will be entitled to injunctive relief and specific performance, and any other relief allowed under applicable law (including monetary damages, if appropriate) without any requirement to post a bond. MusicPass confidential information includes data, reports and other information we may provide to you from time to time about the fitness industry, your location(s), events and/or other services. Such information is provided for informational purposes only.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>12. LIMITATION OF LIABILITY.</span></p>
        <p className="description-without-margin">In no event shall MusicPass be liable or obligated to you or any third party for any special, incidental, exemplary, consequential, punitive, or indirect damages. In addition, MusicPass shall have no liability to you in connection with any acts or omissions of its members, their guests or any other third parties. Except in respect of an intentional violation by us of our obligations under section 7, MusicPass’ sole and complete liability to partner for any claims arising out of or relating to this agreement is limited to payment of the unpaid fees due to partner pursuant to section 2. This limitation of liability applies to the maximum extent permitted by applicable law and notwithstanding the failure of any limited remedy.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>13. DIGITAL.</span></p>
        <p className="description-without-margin">1.	Digital Content. MusicPass may enable partners to make livestream and/or pre-recorded audio, video, and/or other digital content (collectively, “<span style={{fontWeight:""}}>Digital Content</span>”) available through the Website or other platforms. You grant MusicPass and its affiliates all rights needed to use the Digital Content and associated intellectual property (including to modify, reproduce, publicly display, distribute, broadcast, transmit, stream, publish, publicly perform, record, transfer, and sublicense it) worldwide in all applicable media and formats currently existing or hereinafter developed (including MusicPass’ platform and applicable third parties’ streaming, conferencing, and hosting services).</p>
        <p className="description-without-margin">2.	Representations. You represent, warrant, and covenant that (i) you have and will maintain all rights needed from all applicable third parties, including streaming and conferencing services, Digital Content rightsholders and contributors, such as photographers, videographers, instructors, and actors, and owners of musical compositions and sound recordings, for you, MusicPass, and applicable third parties to lawfully use the Digital Content; (ii) no action or payment is or will be needed from MusicPass to lawfully use the Digital Content; (iii) your Digital Content does not and will not contain any material that is illegal, hateful, obscene, unsafe, harmful, or otherwise inappropriate; and (iv) you will take measures needed to respect users’ privacy and rights, including adequately explaining the default settings of any streaming or conferencing system you use. You agree to indemnify, defend, and hold harmless MusicPass and its officers, directors, employees, and affiliates from and against and Losses arising out of or relating to the Digital Content (and MusicPass’ use or nonuse thereof) or Partner’s breach of this Section (Digital).</p>
        <p className="description-without-margin">3.	Payments for Digital. For each legitimate and bona fide livestream Digital Content session that a MusicPass user purchases to reserve or reserves using credits through the Website and successfully attended, you’ll earn the rate applicable to the livestream Digital Content for the applicable time period reflected in MusicPass’ systems (such as the Partner dashboard), unless we agree otherwise in writing. The rate must not be higher than Partner’s direct rate for the offering, and MusicPass is entitled to reimbursement if MusicPass pays a higher rate. Notwithstanding any language to the contrary herein or in your Partner Agreement, unless we otherwise agree in writing:</p>
        <p className="description-without-margin">i. no payment for Digital Content will be earned (and if paid, MusicPass will be entitled to reimbursement) for reservations that are, in MusicPass’ determination: (1) not attended; (2) booked illegitimately (including using a MusicPass free or discounted trial by any Person you inappropriately encouraged or incentivized or by your employees, staff, contractors, agents, family members, or friends, or otherwise booked illegitimately or in connection with fraud, bad faith, or in violation of MusicPass’ user terms); or (3) for non-livestream content (such as pre-recorded content); and</p>
        <p className="description-without-margin">ii. the definition of Qualifying Attendances above (and the rates and payment schedule applicable to Qualifying Attendances) do not apply to Digital Content.</p>
        <p className="description-without-margin">4.	Miscellaneous. If a user reserves a Digital Content spot through MusicPass during the term of your Partner Agreement, you agree to fulfill it. MusicPass will determine the categorization, placement, layout and presentation of the Digital Content. Partner agrees to comply with MusicPass’ guidelines (e.g., regarding formatting) in order to facilitate featuring the Digital Content. MusicPass is not obligated to use or store all or any portion of Digital Content. Nothing in this Section (Digital) limits MusicPass’ rights under other sections of the Terms. Notwithstanding any language to the contrary herein or in any other agreement between MusicPass and Partner, no single reservation will warrant two payments (so for example, if Partner sells livestream event packs through MusicPass, Partner would not earn payments for both the pack as a whole and the single reservations), and all revenue that Partner earns or receives (or has earned or received) from MusicPass (from Digital Content and/or any other offerings) will count towards any revenue guarantees, and will be recoupable in connection with any prepayments, that MusicPass makes or has made to Partner.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>14. ADD-ON PROGRAM.</span></p>
        <p className="description-without-margin">1.	Add-on Program. MusicPass may enable partners to participate in its Add-on program, through which partners are paid up front for partner offerings purchased by users through MusicPass, rather than being paid on a per-reservation basis as individual events or sessions are attended.</p>
        <p className="description-without-margin">2.	Payment Terms.</p>
        <p className="description-without-margin">i. Partner Revenue for Qualifying Add-on Purchases. If you participate in the Add-on program:</p>
        <p className="description-without-margin">A. For each Qualifying Add-on Purchase completed after April 1, 2022 at 11:59pm ET, you will earn 76.5% of the Partner Retail Rate, which includes any applicable tax, except as otherwise stated herein or agreed in writing.</p>
        <p className="description-without-margin">B. If you earn revenue for a Qualifying Add-on Purchase in accordance with this section, individual events or sessions reserved in connection with the Add-on will not count as Qualifying Attendances, and you will not earn revenue or any form of compensation for such reservations other than the revenue described in this section.</p>
        <p className="description-without-margin">ii. Pricing Integrity. Notwithstanding any language to the contrary in the Terms or in any agreement between Partner and MusicPass: You are responsible for providing true and accurate information about your pricing. If the pricing you provide (or the pricing on which your payouts are based) is higher than the pricing you’ve used in non-MusicPass channels, your earned revenue (and your rates going forward) may be reduced accordingly, and for any overpayments already made, MusicPass shall be entitled to either receive reimbursement from you for the difference between the amount paid to you and the amount you should have earned, or to deduct such difference from payments to you.</p>
        <p className="description-without-margin">iii. Payment Schedule. Payments for Qualifying Add-on Purchases will be sent periodically, within 15 business days after the last day of the month.</p>
        <p className="description-without-margin">iv. Refunds/Reimbursements. If Partner or Partner’s personnel receives a cancellation or refund request, Partner should contact MusicPass and not provide a refund directly or take any other responsive action, unless MusicPass provides written instructions to the contrary. MusicPass may issue refunds to users as required by law or in its discretion. Notwithstanding any language to the contrary in the Agreement, if MusicPass issues (or confirms that it is planning to issue) a full or partial refund to a purchaser of your Add-on, MusicPass shall have the right to be reimbursed for the applicable amount by Partner or to deduct the applicable amount from payments to Partner in MusicPass’ discretion; and if MusicPass requests that Partner issue a refund to a user directly instead of reimbursing MusicPass, Partner shall follow MusicPass’ instructions. Partner’s obligations under this section shall apply in all events, including if you are not able to provide the applicable service.</p>
        <p className="description-without-margin">3.	Fulfilment.</p>
        <p className="description-without-margin">i. Reservations. Unless otherwise agreed by MusicPass in writing, users must make reservations through the MusicPass platform (rather than directly with Partner).</p>
        <p className="description-without-margin">ii. Access. Partner shall grant MusicPass and its users equal or greater access to Partner’s venues, schedules, events, other offerings, and spots as Partner’s other customers; Partner shall not grant any direct customer access broader than that granted to MusicPass users. Partner shall enable every user who purchases an Add-on to redeem all sessions associated with it without restriction, pursuant to the terms communicated to the user at point of purchase through MusicPass and the terms herein (including not charging users for access, activation, or any other fees or costs, not requiring any minimum term commitment, where applicable, allowing unlimited access to facilities, and otherwise) through the end of the redemption period communicated to such user at point of purchase through MusicPass, notwithstanding any termination or expiration of this Agreement or any other event.</p>
        <p className="description-without-margin">4.	Business Responsibility. Partner shall be responsible for ensuring compliance with any applicable laws relating to the operation of its business and sales of its offerings, including ensuring that users sign any applicable membership agreement and/or other legally required documentation upon arrival at Partner’s facilities or otherwise.</p>
        <p className="description-without-margin">5.	Definitions. <span style={{fontWeight:""}}>“Add-on”</span> refers to a Partner event package or other Partner offering as made available to users through MusicPass pursuant to terms that are communicated to such users through the MusicPass platform. <span style={{fontWeight:""}}>“Partner Retail Rate”</span> is the lowest price for which the direct Partner offering corresponding to the Add-on has been made available by Partner directly to its own customers or through other non-MusicPass channels up to and including the date of the Qualifying Add-on Purchase, or if there is no corresponding offering that Partner makes available directly, a price that MusicPass determines based on the pricing of other comparable offerings. <span style={{fontWeight:""}}>“Qualifying Add-on Purchase”</span> is a user’s valid and complete purchase of a partner offering through the MusicPass platform as a part of the Add-on program.</p>
        <p className="description-without-margin"><span style={{fontWeight:"bold",fontSize:"28px"}}>&#8226;</span>	<span style={{fontWeight:"bold"}}>15. MISCELLANEOUS.</span></p>
        <p className="description-without-margin">1.	Relationship of the Parties. MusicPass and Partner are independent contractors. Nothing in this Agreement shall be construed as creating a joint venture, partnership, franchise, or an agency relationship between the parties and neither party has the authority, without the other party's prior written approval, to bind or commit the other in any way.</p>
        <p className="description-without-margin">2.	Entire Agreement; Amendments. This Agreement constitutes the entire agreement between the parties relating to its subject matter and supersedes all prior or contemporaneous oral or written agreements concerning such subject matter. MusicPass may amend the Agreement (including the Partner Agreement and/or the Terms) at any time without advance notice or consent. The most recent version of the Terms will be available in the Partner dashboard. Partner agrees that this notification method constitutes adequate notice to inform Partner of any amendments to the Agreement and Partner further agrees to be bound by any such amendments immediately upon such notification, or in accordance with such other time frame that may be communicated by MusicPass. If this Agreement is terminated promptly upon such notification because Partner does not agree to a material change in a material term of the Agreement then MusicPass will continue to honor the terms in effect prior to such amendment for the duration of the applicable termination period. This Agreement may not otherwise be amended or modified except by mutual agreement of authorized representatives of the parties in writing.</p>
        <p className="description-without-margin">3.	Assignment. You will not transfer or assign your rights or obligations under this Agreement, whether by operation of law or otherwise, without the prior written consent of an authorized signatory of MusicPass. We are authorized to transfer or assign this Agreement to a present or future affiliate or pursuant to a merger, consolidation, reorganization or sale of all or substantially all of the assets or business, or by operation of law, without notice to you or to terminate this Agreement in the event of any of the foregoing.</p>
        <p className="description-without-margin">4.	Severability. If any provision of this Agreement is held to be invalid or unenforceable, the validity and enforceability of the remaining provisions of this Agreement shall not be affected.</p>
        <p className="description-without-margin">5.	NO REPRESENTATIONS. Except as expressly stated in this agreement, neither party makes any representations or warranties, express nor implied, including but not limited to any implied warranty of merchantability, fitness for a particular purpose or non-infringement. MusicPass does not warrant or guarantee that the services offered on or through our website will be uninterrupted or error-free or that any partner offering will result in any revenue or profit for partner.</p>
        <p className="description-without-margin">6.	Governing Law; Jurisdiction; Waiver. This Agreement shall be governed by the laws of the State of Florida, without regard to its conflict or choice of law principles. Partner for disputes arising out of or relating to this Agreement shall be limited to a federal or state court located within Miami-Dade County, Florida. Each Party submits to the jurisdiction of such courts. You hereby waive any right to a jury trial and agree that any proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action.</p>
        <p className="description-without-margin">7.	Notices. You agree that all terms and conditions, agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications would satisfy if they were in writing. Except as explicitly stated otherwise, legal notices will be served in English, with respect to MusicPass, at MusicPass LLC, 4000 Ponce De Leon Blvd., Ste 470, Coral Gables, FL 33146, Attention: Legal Department, and, with respect to you, to the email address you provide to us during the registration process (or to any new email address as to which you notify us pursuant to this section. Notice will be deemed given 24 hours after email is sent, unless the sending party is notified that the email address is invalid. Alternatively, we may give you legal notice by mail to the address provided during the registration process (or to any new address as to which you notify us pursuant to this section. Any notice delivered by physical mail will be deemed given the earlier of delivery or three days after the date of mailing.</p>
        <p className="description-without-margin">8.	Headings, Captions & Definitions. The headings and captions in this Agreement are for convenience of reference only and shall in no way modify, or affect the meaning or construction of, any of the terms or provisions hereof. The terms defined herein shall apply equally to both the singular and plural forms and to the correlative forms of such terms. Whenever the context may require, any pronoun shall include the corresponding masculine, feminine and neuter forms. The English language version of these Terms and this Agreement shall prevail if there is a conflict. <span style={{fontWeight:""}}>“Person”</span> (whether or not capitalized) means any natural person, corporation, company, partnership, limited liability company, joint venture, trust, association, sole proprietorship or other entity. The words “<span style={{fontWeight:""}}>include</span>”, “<span style={{fontWeight:""}}>includes</span>” and “<span style={{fontWeight:""}}>including</span>” shall be deemed to be followed by the phrase “<span style={{fontWeight:""}}>without limitation</span>”. “<span style={{fontWeight:""}}>Losses</span>” means claims, lawsuits, investigations, penalties, damages, losses or expenses (including reasonable attorney’s fees). The word “<span style={{fontWeight:""}}>or</span>” is not exclusive. All references to “<span style={{fontWeight:""}}>days</span>” shall be to calendar days and all references to “<span style={{fontWeight:""}}>months</span>” shall be to calendar months, unless otherwise specified.</p>


    </>;

    return (
        <PartnerTermsStyle>
            <HeadingWithContentStyle>
                <Link to="/">
                    <div className="button-wrapper" onClick={(e)=>history.goBack()}>
                        <LeftChevronIcon/> Back To Previous Page
                    </div>
                </Link>

                <h2 className="heading">{"Partner Terms and Conditions"}</h2>
                {content}
            </HeadingWithContentStyle>
        </PartnerTermsStyle>
    );
}
